export type AIProviderId='nvidia-nim'|'openai-compatible'|'aihubmix';
export interface AIProviderConfig{ id:AIProviderId; baseUrl:string; apiKey?:string; model?:string; enabled:boolean; label:string; }
export interface AIMessage{role:'system'|'user'|'assistant';content:string}
export interface AIResult{provider:string;model:string;text:string;usage?:unknown;fallback?:boolean}
export function providerConfigs(env:Record<string,string|undefined>):AIProviderConfig[]{return[
{id:'nvidia-nim',label:'NVIDIA NIM',baseUrl:(env.NVIDIA_NIM_BASE_URL||'https://integrate.api.nvidia.com/v1').replace(/\/$/,''),apiKey:env.NVIDIA_NIM_API_KEY,model:env.NVIDIA_NIM_MODEL,enabled:Boolean(env.NVIDIA_NIM_API_KEY)},
{id:'openai-compatible',label:'OpenAI-compatible provider',baseUrl:(env.AI_PROVIDER_BASE_URL||'').replace(/\/$/,''),apiKey:env.AI_PROVIDER_API_KEY,model:env.AI_PROVIDER_MODEL,enabled:Boolean(env.AI_PROVIDER_BASE_URL&&env.AI_PROVIDER_API_KEY)},
{id:'aihubmix',label:'AIHubMix',baseUrl:(env.AIHUBMIX_BASE_URL||'https://aihubmix.com/v1').replace(/\/$/,''),apiKey:env.AIHUBMIX_API_KEY,model:env.AIHUBMIX_MODEL,enabled:Boolean(env.AIHUBMIX_API_KEY)}]}
function localAnswer(message:string,context?:Record<string,unknown>):AIResult{const c=context&&Object.keys(context).length?` Context supplied: ${Object.keys(context).join(', ')}.`:'';return{provider:'local-deterministic',model:'astrosun-local',fallback:true,text:`AstroSun local assistant is active. No remote AI provider key is configured yet.${c}\n\nQuestion: ${message}`}}
export async function chatWithProviders(messages:AIMessage[],env:Record<string,string|undefined>,context?:Record<string,unknown>):Promise<AIResult>{const providers=providerConfigs(env).filter(x=>x.enabled&&x.apiKey&&x.baseUrl&&x.model);for(const p of providers){try{const response=await fetch(`${p.baseUrl}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.apiKey}`},body:JSON.stringify({model:p.model,messages,temperature:0.2})});if(!response.ok)continue;const data=await response.json();const text=data?.choices?.[0]?.message?.content;if(typeof text==='string'&&text.trim())return{provider:p.label,model:String(data?.model||p.model),text,usage:data?.usage}}catch{}}return localAnswer(messages.filter(x=>x.role==='user').at(-1)?.content||'',context)}
