import React,{useEffect,useRef,useState}from'react';
import{ImagePlus,Mic,Paperclip,Send,Square,Volume2}from'lucide-react';
import{api}from'./production-core.jsx';

export function AIInput({lang='en',page='home',onAnswer}){const[q,setQ]=useState('');const[image,setImage]=useState(null);const[recording,setRecording]=useState(false);const[status,setStatus]=useState('');const rec=useRef(null);const chunks=useRef([]);const fileRef=useRef(null);
useEffect(()=>{const f=e=>{const d=e.detail;if(d?.page===page)onAnswer?.(d)};window.addEventListener('astrosun-ai-answer',f);return()=>window.removeEventListener('astrosun-ai-answer',f)},[page,onAnswer]);
const send=async(text=q)=>{if(!text.trim()&&!image)return;setStatus('…');try{let content=text.trim();if(image)content+=`\n\n[User attached image: ${image.name}]`;const r=await api('/api/ai/chat',{method:'POST',body:JSON.stringify({messages:[{role:'system',content:`You are AstroSun's multimodal evidence-aware astronomy and Jyotisha assistant. Reply entirely in ${lang}. Distinguish measured image facts, astronomical calculations, and traditional interpretation. Never claim astrology, palmistry, or gemstones are scientifically proven causal mechanisms.`},{role:'user',content}],context:{page,language:lang}})});setStatus(r.provider||'AI');onAnswer?.(r);setQ('');setImage(null)}catch(e){setStatus('offline');onAnswer?.({ok:false,error:e.message})}};
const start=async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setStatus('mic unavailable');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const m=new MediaRecorder(stream);rec.current=m;m.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);m.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:'audio/webm'});setQ(x=>x+` [voice ${Math.round(blob.size/1024)}KB captured]`);setRecording(false)};m.start();setRecording(true);setStatus('recording')}catch(e){setStatus('mic denied')}};
const stop=()=>{rec.current?.stop()};
return <div className="jy-input-dock ai-input"><button type="button" title="Attach image" onClick={()=>fileRef.current?.click()}><ImagePlus size={18}/></button><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>setImage(e.target.files?.[0]||null)}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={lang==='hi'?'AstroSun से पूछें…':'Ask AstroSun…'}/>{recording?<button type="button" title="Stop" onClick={stop}><Square size={17}/></button>:<button type="button" title="Speak" onClick={start}><Mic size={18}/></button>}<button type="button" title="Send" onClick={()=>send()}><Send size={18}/></button>{status&&<span className="ai-status">{status}{image?` · ${image.name}`:''}</span>}</div>}
