import React,{useMemo,useState}from'react';
import{CalendarDays,Compass,Diamond,Hand,Orbit,Search,Settings2,Sparkles,Star,Sun,Telescope,Users,Clock3,ChevronRight,MapPin,Mic,ImagePlus,Send}from'lucide-react';
import'./app-home.css';

const T={
 en:{brand:'AstroSun',home:'Home',today:'Today',location:'Location',quick:'Quick actions',kundli:'Kundli',panchanga:'Panchanga',patra:'Patra',muhurta:'Muhurta',ratna:'Ratna Lab',palm:'Show Hand',graha:'Graha Lab',milan:'Kundli Milan',sky:'Sky Lab',todaySky:'Today in the sky',panchangaNow:'Today’s Panchanga',tithi:'Tithi',nak:'Nakshatra',moon:'Moon',open:'Open',ask:'Ask AstroSun…',explore:'Explore',research:'Research',settings:'Settings',language:'Language',getLocation:'Use my location',night:'Night sky',day:'Daylight'},
 hi:{brand:'ऐस्ट्रोसुन',home:'होम',today:'आज',location:'स्थान',quick:'त्वरित कार्य',kundli:'कुंडली',panchanga:'पंचांग',patra:'पत्र',muhurta:'मुहूर्त',ratna:'रत्न प्रयोगशाला',palm:'हाथ दिखाएँ',graha:'ग्रह प्रयोगशाला',milan:'कुंडली मिलान',sky:'आकाश प्रयोगशाला',todaySky:'आज का आकाश',panchangaNow:'आज का पंचांग',tithi:'तिथि',nak:'नक्षत्र',moon:'चंद्रमा',open:'खोलें',ask:'ऐस्ट्रोसुन से पूछें…',explore:'अन्वेषण',research:'अनुसंधान',settings:'सेटिंग्स',language:'भाषा',getLocation:'मेरा स्थान लें',night:'रात्रि आकाश',day:'दिन का आकाश'}
};
const actions=[['kundli','kundli',Compass],['panchanga','panchanga',CalendarDays],['patra','patra',CalendarDays],['muhurta','muhurta',Clock3],['gemstones','ratna',Diamond],['palm','palm',Hand],['graha','graha',Star],['vivah','milan',Users]];

function AIBar({lang,onAsk}){const[q,setQ]=useState('');const[image,setImage]=useState(null);const file=React.useRef(null);const send=()=>{if(!q.trim()&&!image)return;onAsk?.(q.trim()+(image?`\n[चित्र: ${image.name}]`:''));setQ('');setImage(null)};return <div className="ah-ai"><button onClick={()=>file.current?.click()} aria-label="चित्र जोड़ें"><ImagePlus size={19}/></button><input ref={file} type="file" accept="image/*" hidden onChange={e=>setImage(e.target.files?.[0]||null)}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={T[lang].ask}/><button aria-label="आवाज़"><Mic size={19}/></button><button className="send" onClick={send} aria-label="भेजें"><Send size={18}/></button>{image&&<small>{image.name}</small>}</div>}

export function AppHome({lang='en',runtime,profile,onOpen,onAsk,onLanguage,onSettings}){const t=T[lang]||T.en;const[loc,setLoc]=useState(profile?.location?.name||'भारत');const[coords,setCoords]=useState(profile?.location||null);const[locating,setLocating]=useState(false);const now=new Date();const p=runtime?.panchanga;const moon=runtime?.positions?.find(x=>x.body==='Moon');const getLocation=()=>{if(!navigator.geolocation)return;setLocating(true);navigator.geolocation.getCurrentPosition(x=>{setCoords({latitudeDeg:x.coords.latitude,longitudeDeg:x.coords.longitude});setLoc(`${x.coords.latitude.toFixed(2)}°, ${x.coords.longitude.toFixed(2)}°`);setLocating(false)},()=>setLocating(false),{enableHighAccuracy:true,timeout:8000,maximumAge:300000})};const dateLabel=now.toLocaleDateString(lang==='hi'?'hi-IN':'en-IN',{weekday:'long',day:'numeric',month:'long'});const actionRows=useMemo(()=>[actions.slice(0,4),actions.slice(4)],[]);return <div className="ah-app">
 <header className="ah-top"><button className="ah-brand" onClick={()=>onOpen?.('home')}><span className="ah-logo"><Orbit size={23}/></span><span><b>{t.brand}</b><small>{lang==='hi'?'आकाश · ज्योतिष · अनुसंधान':'Astronomy · Jyotisha · Research'}</small></span></button><div className="ah-top-actions"><button onClick={onLanguage} aria-label={t.language}>अ<span>अ</span></button><button onClick={onSettings} aria-label={t.settings}><Settings2 size={20}/></button></div></header>
 <main className="ah-main">
  <section className="ah-welcome"><div><span className="ah-eyebrow">{dateLabel}</span><h1>{t.home}</h1><p>{lang==='hi'?'गणना, आकाश और पारंपरिक ज्योतिष — एक ही कार्यक्षेत्र में।':'Calculated astronomy and traditional Jyotisha in one workspace.'}</p></div><button className="ah-location" onClick={getLocation}><MapPin size={17}/><span>{locating?'…':loc}</span></button></section>
  <section className="ah-section"><div className="ah-section-head"><h2>{t.quick}</h2><span>8</span></div>{actionRows.map((row,i)=><div className="ah-action-row" key={i}>{row.map(([id,key,I])=><button key={id} className="ah-action" onClick={()=>onOpen?.(id)}><span className="ah-action-icon"><I size={21}/></span><span>{t[key]}</span><ChevronRight size={16}/></button>)}</div>)}</section>
  <section className="ah-section"><div className="ah-section-head"><h2>{t.panchangaNow}</h2><button onClick={()=>onOpen?.('panchanga')}>{t.open} <ChevronRight size={15}/></button></div><div className="ah-data-grid"><article><small>{t.tithi}</small><strong>{p?.tithi?.name||'—'}</strong><span>{p?.tithi?.paksha||''}</span></article><article><small>{t.nak}</small><strong>{p?.nakshatra?.name||'—'}</strong><span>{p?.nakshatra?.pada?`पाद ${p.nakshatra.pada}`:''}</span></article><article><small>{t.moon}</small><strong>{moon?`${moon.longitudeDeg.toFixed(1)}°`:'—'}</strong><span>{t.today}</span></article></div></section>
  <section className="ah-section"><div className="ah-section-head"><h2>{t.todaySky}</h2><button onClick={()=>onOpen?.('sky')}>{t.open} <ChevronRight size={15}/></button></div><button className="ah-sky-card" onClick={()=>onOpen?.('sky')}><span className="ah-sky-orb"><Sun size={28}/></span><span><b>{lang==='hi'?'सौर मंडल प्रयोगशाला':'Solar-system laboratory'}</b><small>{lang==='hi'?'वास्तविक समय, ग्रहों पर टैप करके विस्तृत डेटा देखें':'Real-time motion, tap any body for detailed data'}</small></span><Telescope size={22}/></button></section>
  <AIBar lang={lang} onAsk={onAsk}/>
 </main>
 <nav className="ah-nav"><button className="on" onClick={()=>onOpen?.('home')}><Sparkles/><span>{t.home}</span></button><button onClick={()=>onOpen?.('sky')}><Telescope/><span>{t.explore}</span></button><button onClick={()=>onOpen?.('panchanga')}><CalendarDays/><span>{lang==='hi'?'कैलेंडर':'Calendar'}</span></button><button onClick={()=>onOpen?.('research')}><Search/><span>{t.research}</span></button><button onClick={onSettings}><Settings2/><span>{t.settings}</span></button></nav>
 </div>}
