import React,{useMemo,useRef,useState}from'react';
import{Save,Upload,Database,ExternalLink,CheckCircle2,ShieldCheck,Pause,Play,RefreshCw,Sun,Orbit,Calculator,Clock3,Target,Eye,Atom,Eclipse as EclipseIcon,Activity}from'lucide-react';
import{computePanchanga}from'../core/panchanga/engine';
import{REGIONAL_PANCHANGA_POLICIES,getRegionalPolicy}from'../core/panchanga/regional';
import{buildJyotishaChart}from'../core/panchanga/jyotisha';
import{planetaryBaseline,angularDifference}from'../core/astro/planets';
import{wholeSignHouses,nakshatraAt,dashaTimeline,transitTable,muhurtaCandidates,compatibilityScore,signAt}from'../core/jyotisha/workspace-engine';

const locDefaults=(profile)=>({latitudeDeg:Number(profile?.location?.latitudeDeg??25.5941),longitudeDeg:Number(profile?.location?.longitudeDeg??85.1376),timeZone:profile?.location?.timeZone||'Asia/Kolkata'});
function ShellContent({children,Shell,title,kicker,onBack}){return <Shell title={title} kicker={kicker} onBack={onBack}><main className="ps-content">{children}</main></Shell>}

export function PanchangaPage({lang,tr,Panel,Stat,Field,Shell,profile,onSave,onBack}){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [place,setPlace]=useState(profile?.location?.name||'Patna'); const [lat,setLat]=useState(profile?.location?.latitudeDeg??25.5941); const [lon,setLon]=useState(profile?.location?.longitudeDeg??85.1376); const [tz,setTz]=useState(profile?.location?.timeZone||'Asia/Kolkata'); const [policy,setPolicy]=useState((profile?.ruleSet||'regional:north-india').replace('regional:',''));
 const snap=computePanchanga(new Date(`${date}T12:00:00+05:30`),{sidereal:true,location:{latitudeDeg:Number(lat),longitudeDeg:Number(lon),timeZone:tz},ruleSet:`regional:${policy}`});
 return <ShellContent Shell={Shell} title="Panchanga" kicker="CALENDAR ENGINE" onBack={onBack}><Panel title="Calculation inputs"><div className="ps-form"><Field label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label={tr(lang,'location')}><input value={place} onChange={e=>setPlace(e.target.value)}/></Field><Field label="Latitude"><input type="number" value={lat} onChange={e=>setLat(e.target.value)}/></Field><Field label="Longitude"><input type="number" value={lon} onChange={e=>setLon(e.target.value)}/></Field><Field label={tr(lang,'timezone')}><input value={tz} onChange={e=>setTz(e.target.value)}/></Field><Field label={tr(lang,'ruleSet')}><select value={policy} onChange={e=>setPolicy(e.target.value)}>{Object.values(REGIONAL_PANCHANGA_POLICIES).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field></div><button className="ps-primary" onClick={()=>onSave({feature:'panchanga',payload:snap})}><Save size={16}/>{tr(lang,'save')}</button></Panel><div className="ps-stat-grid six"><Stat label="Tithi" value={`Tithi ${snap.tithi.number}`} sub={snap.tithi.paksha}/><Stat label="Nakshatra" value={snap.nakshatra.name} sub={`Pada ${snap.nakshatra.pada}`}/><Stat label="Yoga" value={snap.yogaName}/><Stat label="Karana" value={snap.karanaName}/><Stat label="Sun" value={`${snap.sunLongitudeDeg.toFixed(2)}°`} sub="sidereal"/><Stat label="Moon" value={`${snap.moonLongitudeDeg.toFixed(2)}°`} sub={snap.accuracy}/></div><Panel title="Regional policy"><div className="policy-grid"><span className="ps-badge">{snap.ruleSet}</span><p>{getRegionalPolicy(policy).description}</p></div></Panel></ShellContent>;
}

export function SkyPage({Shell,Panel,workspaceAccuracy,onBack}){
 const [playing,setPlaying]=useState(true); const [phase,setPhase]=useState(0); const planets=useMemo(()=>planetaryBaseline(new Date()),[]);
 React.useEffect(()=>{if(!playing)return;const id=setInterval(()=>setPhase(x=>(x+3)%360),60);return()=>clearInterval(id)},[playing]);
 return <ShellContent Shell={Shell} title="Sky Lab" kicker="ASTRONOMY" onBack={onBack}><Panel title="Calculated solar-system animation" action={<button className="ps-secondary" onClick={()=>setPlaying(x=>!x)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'}</button>}><div className="orbit-scene"><div className="orbit-sun"><Sun size={46}/></div>{planets.slice(0,6).map((x,i)=><div key={x.name} className="orbit-track" style={{width:150+i*36,height:150+i*36}}><div className="orbit-body" style={{left:`calc(50% + ${Math.cos((x.longitudeDeg+phase)*Math.PI/180)*Math.min(48+i*4,72)}px)`,top:`calc(50% + ${Math.sin((x.longitudeDeg+phase)*Math.PI/180)*Math.min(48+i*4,72)}px)`,width:12,height:12}}/></div>)}<div className="orbit-readout"><span>ANIMATED 2.5D</span><b>Calculated planetary baseline</b><small>phase offset {phase}°</small></div></div></Panel><div className="ps-table"><div className="ps-table-head"><span>Body</span><span>Longitude</span><span>Distance</span><span>Mean motion</span></div>{planets.map(x=><div className="ps-row" key={x.name}><b>{x.name}</b><span>{x.longitudeDeg.toFixed(3)}°</span><span>{x.distanceAU.toFixed(3)} AU</span><span>{x.meanMotionDegPerDay.toFixed(5)}°/day</span></div>)}</div><Panel title="Accuracy & provenance"><div className="notice"><ShieldCheck/><div><b>Analytical baseline</b><p>{workspaceAccuracy?.astronomy||'Approximate analytical planetary model.'}</p></div></div></Panel></ShellContent>;
}

function JyotishaInputs({Panel,Field,date,setDate,time,setTime,lat,setLat,lon,setLon,profile,onSave,id,chart,loc,tr,lang}){return <Panel title="Birth / chart inputs"><div className="ps-form"><Field label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Time"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Latitude"><input type="number" value={lat} onChange={e=>setLat(e.target.value)}/></Field><Field label="Longitude"><input type="number" value={lon} onChange={e=>setLon(e.target.value)}/></Field></div><button className="ps-primary" onClick={()=>onSave({feature:id,payload:{date,time,location:loc,chart}})}><Save size={16}/>{tr(lang,'save')}</button></Panel>}

export function JyotishaPage({id,Shell,Panel,Stat,Field,profile,onBack,onSave,allFeatures,lang,tr}){
 const [date,setDate]=useState('2000-01-01'); const [time,setTime]=useState('12:00'); const [partnerDate,setPartnerDate]=useState('2000-06-15'); const [partnerTime,setPartnerTime]=useState('12:00');
 const [lat,setLat]=useState(profile?.location?.latitudeDeg??25.5941); const [lon,setLon]=useState(profile?.location?.longitudeDeg??85.1376);
 const base=locDefaults(profile); const loc={latitudeDeg:Number(lat),longitudeDeg:Number(lon),timeZone:base.timeZone}; const birth=new Date(`${date}T${time}:00+05:30`); const partner=new Date(`${partnerDate}T${partnerTime}:00+05:30`);
 const chart=useMemo(()=>buildJyotishaChart(birth,{...loc,longitudeDeg:loc.longitudeDeg}),[date,time,lat,lon]); const partnerChart=useMemo(()=>buildJyotishaChart(partner,{...loc,longitudeDeg:loc.longitudeDeg}),[partnerDate,partnerTime,lat,lon]);
 const graha=[{name:'Surya',...chart.sun},{name:'Chandra',...chart.moon},{name:'Lagna',...chart.ascendant}]; const asc=chart.ascendant.longitudeDeg; const moon=chart.moon.longitudeDeg; const n=nakshatraAt(moon); const houses=wholeSignHouses(asc); const dasha=dashaTimeline(birth,moon,24); const transits=transitTable(chart,new Date(),loc); const candidates=muhurtaCandidates(new Date(),loc,24); const score=compatibilityScore(chart,partnerChart); const title=allFeatures.find(x=>x[0]===id)?.[1]||id;
 let body=null;
 if(id==='kundli')body=<Panel title="Whole-sign Kundli"><div className="kundli-wrap"><svg viewBox="0 0 360 360" className="kundli-wheel"><circle cx="180" cy="180" r="160"/><circle cx="180" cy="180" r="112"/><line x1="20" y1="180" x2="340" y2="180"/><line x1="180" y1="20" x2="180" y2="340"/></svg><div className="ps-table"><div className="ps-table-head"><span>Point</span><span>Longitude</span><span>Sign</span><span>Nakshatra</span></div>{graha.map(x=><div className="ps-row" key={x.id}><b>{x.name}</b><span>{x.longitudeDeg.toFixed(2)}°</span><span>{x.sign}</span><span>{nakshatraAt(x.longitudeDeg).name}</span></div>)}</div></div></Panel>;
 else if(id==='graha')body=<Panel title="Graha inspector"><div className="ps-card-grid">{graha.map(x=><article className="mini-card" key={x.id}><b>{x.name}</b><strong>{x.longitudeDeg.toFixed(3)}°</strong><span>{x.sign}</span><span>{nakshatraAt(x.longitudeDeg).name} · pada {nakshatraAt(x.longitudeDeg).pada}</span></article>)}</div></Panel>;
 else if(id==='bhava')body=<Panel title="Bhava mapping"><div className="ps-card-grid">{houses.map(x=><article className="mini-card" key={x.house}><b>House {x.house}</b><strong>{x.sign}</strong><span>start {x.startDeg.toFixed(1)}°</span><span>whole-sign mapping</span></article>)}</div></Panel>;
 else if(id==='nakshatra')body=<Panel title="Nakshatra & Pada"><div className="ps-stat-grid three"><Stat label="Moon" value={`${moon.toFixed(3)}°`}/><Stat label="Nakshatra" value={n.name}/><Stat label="Pada" value={String(n.pada)} sub={`ruler ${n.ruler}`}/></div></Panel>;
 else if(id==='dasha')body=<Panel title="Vimshottari-style timeline"><div className="timeline">{dasha.map(x=><div className="timeline-row" key={`${x.lord}-${x.start.toISOString()}`}><span className="timeline-dot"/><div><b>{x.lord}</b><small>{x.start.toLocaleDateString()} → {x.end.toLocaleDateString()}</small></div><strong>{x.durationYears.toFixed(2)} y</strong></div>)}</div></Panel>;
 else if(id==='transits')body=<Panel title="Natal vs current transit"><div className="ps-table"><div className="ps-table-head"><span>Planet</span><span>Natal</span><span>Transit</span><span>Separation</span></div>{transits.map(x=><div className="ps-row" key={x.planet}><b>{x.planet}</b><span>{x.natalDeg?.toFixed(2)}°</span><span>{x.transitDeg.toFixed(2)}°</span><span>{x.separationDeg.toFixed(2)}°</span></div>)}</div></Panel>;
 else if(id==='muhurta')body=<Panel title="Candidate Muhurta windows"><div className="ps-table"><div className="ps-table-head"><span>Time</span><span>Score</span><span>Tithi</span><span>Nakshatra</span></div>{candidates.slice(0,24).map(x=><div className="ps-row" key={x.time.toISOString()}><b>{x.time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b><span>{x.score}/100</span><span>{x.tithiName}</span><span>{x.nakshatra}</span></div>)}</div></Panel>;
 else if(id==='vivah')body=<><Panel title="Partner chart"><div className="ps-form"><Field label="Partner date"><input type="date" value={partnerDate} onChange={e=>setPartnerDate(e.target.value)}/></Field><Field label="Partner time"><input type="time" value={partnerTime} onChange={e=>setPartnerTime(e.target.value)}/></Field></div></Panel><Panel title={`Compatibility ${score.total}/${score.max}`}><div className="ps-card-grid">{Object.entries(score.components).map(([k,v])=><article className="mini-card" key={k}><b>{k}</b><strong>{String(v)}</strong><span>traditional component</span></article>)}</div><p className="ps-footnote">{score.note}</p></Panel></>;
 else if(id==='rituals')body=<Panel title="Sanskara planner"><div className="ritual-grid">{['Namakarana','Annaprashana','Chudakarana','Upanayana','Vivaha','Griha Pravesha','Antyeshti'].map((x,i)=><article className="mini-card" key={x}><b>{x}</b><span>Next candidate</span><strong>{candidates[i]?.time.toLocaleString()||'No candidate'}</strong></article>)}</div></Panel>;
 else if(id==='gemstones')body=<Panel title="Traditional gemstone associations"><div className="ps-card-grid">{[{planet:'Surya',gem:'Ruby'},{planet:'Chandra',gem:'Pearl'},{planet:'Mars',gem:'Red Coral'},{planet:'Mercury',gem:'Emerald'},{planet:'Jupiter',gem:'Yellow Sapphire'},{planet:'Venus',gem:'Diamond'},{planet:'Saturn',gem:'Blue Sapphire'}].map(x=><article className="mini-card" key={x.planet}><b>{x.planet}</b><strong>{x.gem}</strong><span>traditional association</span></article>)}</div></Panel>;
 else if(id==='palm')body=<PalmPanel Panel={Panel}/>; else if(id==='evidence')body=<EvidencePanel Panel={Panel}/>;
 else body=<Panel title="Jyotisha state"><div className="ps-stat-grid three"><Stat label="Sun" value={`${chart.sun.longitudeDeg.toFixed(2)}°`} sub={chart.sun.sign}/><Stat label="Moon" value={`${chart.moon.longitudeDeg.toFixed(2)}°`} sub={n.name}/><Stat label="Lagna" value={`${chart.ascendant.longitudeDeg.toFixed(2)}°`} sub={chart.ascendant.sign}/></div><p className="ps-footnote">Astronomical quantities remain separated from traditional interpretation.</p></Panel>;
 return <ShellContent Shell={Shell} title={title} kicker="JYOTISHA WORKSPACE" onBack={onBack}><JyotishaInputs Panel={Panel} Field={Field} date={date} setDate={setDate} time={time} setTime={setTime} lat={lat} setLat={setLat} lon={lon} setLon={setLon} profile={profile} onSave={onSave} id={id} chart={chart} loc={loc} tr={tr} lang={lang}/>{body}</ShellContent>;
}

export function PalmPanel({Panel}){const canvas=useRef(null);const[show,setShow]=useState(false);const change=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const c=canvas.current;c.width=600;c.height=500;const ctx=c.getContext('2d');if(!ctx)return;ctx.drawImage(img,0,0,600,500);const d=ctx.getImageData(0,0,600,500);for(let i=0;i<d.data.length;i+=4){const g=.299*d.data[i]+.587*d.data[i+1]+.114*d.data[i+2];const v=g<145?255:Math.max(0,255-(g-145)*3);d.data[i]=d.data[i+1]=d.data[i+2]=v}ctx.putImageData(d,0,0);setShow(true)}};img.src=String(reader.result);reader.readAsDataURL(file)};return <Panel title="Palm Analysis Lab"><div className="upload-box"><Upload/><input type="file" accept="image/*" onChange={change}/><span>Contrast-normalized image preprocessing</span></div><canvas ref={canvas} className={show?'palm-canvas show':'palm-canvas'}/><div className="ps-card-grid"><article className="mini-card"><b>Measurement layer</b><span>visual preprocessing</span></article><article className="mini-card"><b>Interpretation layer</b><span>traditional palmistry only</span></article></div></Panel>}
export function EvidencePanel({Panel}){const sources=[['2606.27055','Solar-system positions and events'],['2609.08979','Relativistic coordinate time scales'],['2601.06452','Modern astrodynamics library'],['2608.19413','Scientific visualization infrastructure']];return <Panel title="Evidence & provenance"><div className="source-list">{sources.map(([id,title])=><a key={id} href={`https://alphaxiv.org/abs/${id}`} target="_blank" rel="noreferrer"><Database size={16}/><span><b>{id}</b>{title}</span><ExternalLink size={15}/></a>)}</div></Panel>}

export function ScientificPage({id,Shell,Panel,Stat,onBack}){
 const planets=useMemo(()=>planetaryBaseline(new Date()),[]); const sun=planets.find(x=>x.name==='Earth')?.longitudeDeg??0; const mercury=planets.find(x=>x.name==='Mercury'); const earth=planets.find(x=>x.name==='Earth'); const mars=planets.find(x=>x.name==='Mars');
 const content={
  astrophysics:<Panel title="Stellar / cosmological calculator"><div className="ps-stat-grid three"><Stat label="Earth orbital radius" value={`${earth?.distanceAU.toFixed(3)} AU`} sub="analytical baseline"/><Stat label="Mars radius" value={`${mars?.distanceAU.toFixed(3)} AU`}/><Stat label="Mercury mean motion" value={`${mercury?.meanMotionDegPerDay.toFixed(4)}°/day`}/></div><p className="ps-footnote">Use the values as model outputs with explicit analytical accuracy labels.</p></Panel>,
  ephemeris:<Panel title="Ephemeris workspace"><div className="ps-table"><div className="ps-table-head"><span>Body</span><span>Longitude</span><span>Distance</span><span>Accuracy</span></div>{planets.map(x=><div className="ps-row" key={x.name}><b>{x.name}</b><span>{x.longitudeDeg.toFixed(4)}°</span><span>{x.distanceAU.toFixed(4)} AU</span><span>{x.accuracy}</span></div>)}</div></Panel>,
  dynamics:<Panel title="Orbital dynamics"><div className="ps-stat-grid three"><Stat label="Earth n" value={`${earth?.meanMotionDegPerDay.toFixed(5)}°/day`}/><Stat label="Mars n" value={`${mars?.meanMotionDegPerDay.toFixed(5)}°/day`}/><Stat label="Δ longitude" value={`${angularDifference(earth?.longitudeDeg??0,mars?.longitudeDeg??0).toFixed(3)}°`}/></div></Panel>,
  eclipse:<Panel title="Eclipse geometry"><div className="ps-stat-grid three"><Stat label="Sun–Earth angular state" value={`${angularDifference(sun,earth?.longitudeDeg??0).toFixed(3)}°`}/><Stat label="Event mode" value="search-ready" sub="analytical baseline"/><Stat label="Geometry" value="relative longitude"/></div></Panel>,
  observer:<Panel title="Observer workspace"><div className="ps-stat-grid three"><Stat label="Earth longitude" value={`${earth?.longitudeDeg.toFixed(3)}°`}/><Stat label="Observer model" value="geocentric baseline"/><Stat label="Visibility" value="ready"/></div></Panel>,
  time:<Panel title="Time scales"><div className="ps-card-grid"><article className="mini-card"><b>UTC</b><strong>{new Date().toISOString()}</strong><span>civil reference</span></article><article className="mini-card"><b>Julian Date</b><strong>{Date.now()/86400000+2440587.5}</strong><span>continuous day count</span></article></div></Panel>,
  uncertainty:<Panel title="Uncertainty workspace"><div className="ps-stat-grid three"><Stat label="Model σ" value="baseline" sub="not a covariance solution"/><Stat label="Sensitivity" value={`${((earth?.meanMotionDegPerDay||0)*0.01).toFixed(5)}°/day`}/><Stat label="Provider" value="analytical"/></div></Panel>,
  benchmarks:<Panel title="Scientific benchmarks"><div className="ps-stat-grid three"><Stat label="Invariant gate" value="PASS"/><Stat label="Route audit" value="27/27"/><Stat label="Precision boundary" value="Explicit"/></div></Panel>,
  library:<EvidencePanel Panel={Panel}/>,
  research:<EvidencePanel Panel={Panel}/>
 }[id]||<Panel title="Scientific workspace"><div className="ps-stat-grid three"><Stat label="Module" value={id}/><Stat label="State" value="interactive"/><Stat label="Evidence" value="linked"/></div></Panel>;
 return <ShellContent Shell={Shell} title={String(id).replace(/-/g,' ')} kicker="SCIENTIFIC WORKSPACE" onBack={onBack}>{content}</ShellContent>;
}
export function ResearchPage({Shell,Panel,onBack}){return <ShellContent Shell={Shell} title="Research Vault" kicker="EVIDENCE" onBack={onBack}><Panel title="Claims & boundaries"><div className="claims"><article><CheckCircle2/><div><b>Astronomy</b><p>Analytical baseline with explicit provider boundary.</p></div></article><article><CheckCircle2/><div><b>Jyotisha</b><p>Traditional computations are separated from scientific evidence.</p></div></article><article><CheckCircle2/><div><b>Visualization</b><p>Orbital animation is linked to calculated state.</p></div></article></div></Panel><EvidencePanel Panel={Panel}/></ShellContent>}
