import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Compass,Crosshair,Globe2,Info,MapPin,Pause,Play,RefreshCw,Search,Sun as SunIcon,Telescope,TimerReset,ZoomIn,ZoomOut}from'lucide-react';
import{planetaryBaseline}from'../core/astro/planets';
import{julianDate,sunEclipticLongitude,moonEclipticPosition}from'../core/astro/ephemeris';
import'./sky-lab.css';

const NAK=['अश्विनी','भरणी','कृत्तिका','रोहिणी','मृगशिरा','आर्द्रा','पुनर्वसु','पुष्य','आश्लेषा','मघा','पूर्वा फाल्गुनी','उत्तरा फाल्गुनी','हस्त','चित्रा','स्वाती','विशाखा','अनुराधा','ज्येष्ठा','मूल','पूर्वाषाढ़ा','उत्तराषाढ़ा','श्रवण','धनिष्ठा','शतभिषा','पूर्वाभाद्रपद','उत्तराभाद्रपद','रेवती'];
const RASHI=['मेष','वृषभ','मिथुन','कर्क','सिंह','कन्या','तुला','वृश्चिक','धनु','मकर','कुंभ','मीन'];
const BODY=['सूर्य','बुध','शुक्र','पृथ्वी','मंगल','बृहस्पति','शनि','अरुण','वरुण','प्लूटो'];
const EN={सूर्य:'Sun',बुध:'Mercury',शुक्र:'Venus',पृथ्वी:'Earth',मंगल:'Mars',बृहस्पति:'Jupiter',शनि:'Saturn',अरुण:'Uranus',वरुण:'Neptune',प्लूटो:'Pluto'};
const SIZE={सूर्य:42,बुध:7,शुक्र:9,पृथ्वी:10,मंगल:8,बृहस्पति:18,शनि:15,अरुण:12,वरुण:12,प्लूटो:5};
const SPEED={सूर्य:0.9856,बुध:4.092,शुक्र:1.602,पृथ्वी:0.9856,mangal:0};
const norm=x=>((x%360)+360)%360;
function gmst(jd){const d=jd-2451545;return norm(280.46061837+360.98564736629*d)}
function horizon(lon,latDeg,observerLat,observerLon,jd){const e=23.4393*Math.PI/180;const l=lon*Math.PI/180,b=latDeg*Math.PI/180;const ra=Math.atan2(Math.sin(l)*Math.cos(e)-Math.tan(b)*Math.sin(e),Math.cos(l))*180/Math.PI/15;const dec=Math.asin(Math.sin(b)*Math.cos(e)+Math.cos(b)*Math.sin(e)*Math.sin(l))*180/Math.PI;const lst=(gmst(jd)+observerLon)/15;const H=((lst-ra+12)%24)-12;const h=observerLat*Math.PI/180;const hd=dec*Math.PI/180;const hr=H*15*Math.PI/180;const alt=Math.asin(Math.sin(h)*Math.sin(hd)+Math.cos(h)*Math.cos(hd)*Math.cos(hr))*180/Math.PI;let az=Math.atan2(-Math.sin(hr),Math.tan(hd)*Math.cos(h)-Math.sin(h)*Math.cos(hr))*180/Math.PI+180;az=norm(az);return{alt,az,ra:ra*15,dec}}
function nak(lon){const s=norm(lon-24.14);const i=Math.floor(s/(360/27));const pada=Math.floor((s%(360/27))/(360/108))+1;return{name:NAK[i],pada,ruler:['केतु','शुक्र','सूर्य','चंद्र','मंगल','राहु','बृहस्पति','शनि','बुध'][i%9]}}
function sidereal(lon){return norm(lon-24.14)}
function fmtTime(d){return d.toLocaleTimeString('hi-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function bodyData(now,lat,lon){const jd=julianDate(now);const base=planetaryBaseline(now);const sun=sunEclipticLongitude(jd);const moon=moonEclipticPosition(jd);const rows=[{name:'सूर्य',lon:sun,dist:1,motion:.9856,lat:0},{name:'चंद्रमा',lon:moon.longitudeDeg,dist:moon.distanceAU,motion:13.176,lat:moon.latitudeDeg},...base.map(x=>({name:Object.entries(EN).find(([,v])=>v===x.name)?.[0]||x.name,lon:x.longitudeDeg,dist:x.distanceAU,motion:x.meanMotionDegPerDay,lat:0}))];return rows.map(x=>{const h=horizon(x.lon,x.lat,lat,lon,jd);const s=sidereal(x.lon);return{...x,sidereal:s,rashi:RASHI[Math.floor(s/30)],nak:nak(x.lon),...h,visible:h.alt>0,daySun:h.alt>0}})}

export function SkyLab({lang='hi',onBack,onOpen,onAsk,profile}){const[observer,setObserver]=useState({lat:Number(profile?.location?.latitudeDeg??25.5941),lon:Number(profile?.location?.longitudeDeg??85.1376),name:profile?.location?.name||'भारत'});const[now,setNow]=useState(new Date());const[playing,setPlaying]=useState(true);const[rate,setRate]=useState(1);const[focus,setFocus]=useState('सूर्य');const[tab,setTab]=useState('आकाश');const[zoom,setZoom]=useState(1);const[locating,setLocating]=useState(false);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setNow(new Date()),250);return()=>clearInterval(id)},[playing]);const data=useMemo(()=>bodyData(now,observer.lat,observer.lon),[now,observer.lat,observer.lon]);const selected=data.find(x=>x.name===focus)||data[0];const getLocation=()=>{if(!navigator.geolocation)return;setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setObserver({lat:p.coords.latitude,lon:p.coords.longitude,name:`${p.coords.latitude.toFixed(3)}°, ${p.coords.longitude.toFixed(3)}°`});setLocating(false)},()=>setLocating(false),{enableHighAccuracy:true,timeout:10000,maximumAge:300000})};const setFocusBody=x=>{setFocus(x.name);setTab('विवरण')};const speed=rate===1?'1×':rate===60?'1 min/s':rate===3600?'1 hr/s':'1 day/s';const localDay=selected?.daySun;return <div className="sky-lab"><header className="sl-top"><button onClick={onBack} className="sl-back"><ArrowLeft/></button><div><small>ASTRONOMY · REAL-TIME LAB</small><h1>आकाश प्रयोगशाला</h1></div><div className="sl-top-right"><button onClick={getLocation} title="स्थान"><MapPin/><span>{locating?'…':observer.name}</span></button><button onClick={()=>setPlaying(x=>!x)}>{playing?<Pause/>:<Play/>}</button><button onClick={()=>setNow(new Date())}><RefreshCw/></button></div></header>
 <main className="sl-main">
  <section className="sl-status"><div><span>अवलोकन समय</span><b>{now.toLocaleDateString('hi-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b><small>{fmtTime(now)} · {observer.lat.toFixed(3)}°, {observer.lon.toFixed(3)}°</small></div><div className={localDay?'day':'night'}><span>{localDay?'दिन का आकाश':'रात्रि आकाश'}</span><b>{selected?.alt.toFixed(1)}°</b><small>{selected?.name} की ऊँचाई</small></div></section>
  <section className="sl-lab-card"><div className="sl-lab-head"><div><small>सौर मंडल · गणना आधारित दृश्य</small><h2>सूर्य से प्लूटो तक</h2></div><div className="sl-controls"><button onClick={()=>setZoom(z=>Math.max(.65,z-.15))}><ZoomOut/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.7,z+.15))}><ZoomIn/></button></div></div><div className="sl-space" style={{'--zoom':zoom}}><div className="sl-starfield"/><div className="sl-sun" onClick={()=>setFocusBody(data.find(x=>x.name==='सूर्य'))}><div className="sl-corona"/><SunIcon/><small>सूर्य</small></div>{data.filter(x=>x.name!=='सूर्य').map((x,i)=>{const r=58+i*25;const a=(x.lon+(now.getTime()%86400000)/86400000*x.motion)*Math.PI/180;return <button key={x.name} className={`sl-body sl-body-${i}`} style={{'--r':`${r}px`,'--a':`${a}rad`,'--size':`${SIZE[x.name]||8}px`}} onClick={()=>setFocusBody(x)}><i/><span>{x.name}</span></button>})}<div className="sl-ecliptic"/></div><div className="sl-timebar"><button onClick={()=>setRate(rate===1?60:rate===60?3600:rate===3600?86400:1)}><TimerReset/> {speed}</button><input type="range" min="0" max="3" value={rate===1?0:rate===60?1:rate===3600?2:3} onChange={e=>setRate([1,60,3600,86400][Number(e.target.value)])}/><button onClick={()=>setPlaying(x=>!x)}>{playing?'रोकें':'चलाएँ'}</button></div></section>
  <div className="sl-tabs">{['आकाश','विवरण','डेटा','घटनाएँ','निरीक्षण'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</div>
  {tab==='आकाश'&&<section className="sl-grid"><article><small>चयनित पिंड</small><h2>{selected.name}</h2><b>{selected.rashi}</b><p>नक्षत्र: <strong>{selected.nak.name}</strong> · पाद {selected.nak.pada}</p><p>दिगंश {selected.az.toFixed(1)}° · ऊँचाई {selected.alt.toFixed(1)}°</p></article><article><small>सूर्य स्थिति</small><h2>{localDay?'अभी दिन है':'अभी रात है'}</h2><p>सूर्य की ऊँचाई: <strong>{data.find(x=>x.name==='सूर्य')?.alt.toFixed(1)}°</strong></p><p>यह स्थिति आपके चुने हुए स्थान और वर्तमान समय से निकाली गई है।</p></article><article><small>त्वरित प्रयोग</small><div className="sl-actions"><button onClick={()=>setTab('डेटा')}>सभी ग्रह डेटा</button><button onClick={()=>setTab('घटनाएँ')}>आज की घटनाएँ</button><button onClick={()=>setTab('निरीक्षण')}>दृश्यता जाँच</button></div></article></section>}
  {tab==='विवरण'&&<section className="sl-detail"><div className="sl-detail-hero"><span className="sl-detail-orb" style={{'--body':focus}}/><div><small>चयनित खगोलीय पिंड</small><h2>{selected.name}</h2><p>{EN[selected.name]||'Celestial body'}</p></div></div><div className="sl-metrics">{[['दीर्घांश',`${selected.lon.toFixed(4)}°`],['निरयन',`${selected.sidereal.toFixed(4)}°`],['राशि',selected.rashi],['नक्षत्र',selected.nak.name],['पाद',selected.nak.pada],['दूरी',`${selected.dist.toFixed(4)} AU`],['ऊँचाई',`${selected.alt.toFixed(2)}°`],['अज़ीमुथ',`${selected.az.toFixed(2)}°`],['दैनिक गति',`${selected.motion.toFixed(5)}°/दिन`]].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div><div className="sl-detail-actions"><button onClick={()=>onOpen?.('panchanga')}>आज का पंचांग</button><button onClick={()=>onOpen?.('graha')}>ग्रह निरीक्षक</button><button onClick={()=>onAsk?.(`${selected.name} की आज की स्थिति, दृश्यता, नक्षत्र और गणना विस्तार से बताओ।`)}>इस पिंड के बारे में पूछें</button></div><p className="sl-note">स्थिति AstroSun के उपलब्ध विश्लेषणात्मक खगोलीय मॉडल से गणना की गई है। इसे उच्च-सटीकता JPL/IAU एपेमेरिस न मानें जब तक उच्च-सटीकता प्रदाता कनेक्ट न किया जाए।</p></section>}
  {tab==='डेटा'&&<section className="sl-table"><div className="sl-table-head"><span>पिंड</span><span>दीर्घांश</span><span>निरयन राशि</span><span>ऊँचाई</span><span>दूरी</span></div>{data.map(x=><button key={x.name} onClick={()=>setFocusBody(x)}><b>{x.name}</b><span>{x.lon.toFixed(3)}°</span><span>{x.rashi}</span><span>{x.alt.toFixed(1)}°</span><span>{x.dist.toFixed(3)} AU</span></button>)}</section>}
  {tab==='घटनाएँ'&&<section className="sl-events"><article><b>दिन / रात</b><span>{localDay?'आपके स्थान पर अभी सूर्य क्षितिज से ऊपर है।':'आपके स्थान पर अभी सूर्य क्षितिज के नीचे है।'}</span></article><article><b>चंद्र स्थिति</b><span>{data.find(x=>x.name==='चंद्रमा')?.nak.name} · {data.find(x=>x.name==='चंद्रमा')?.rashi}</span></article><article><b>ग्रह दृश्यता</b><span>{data.filter(x=>x.name!=='सूर्य'&&x.alt>0).map(x=>x.name).join(' · ')||'इस समय कोई ग्रह क्षितिज से ऊपर नहीं'}</span></article><article><b>अगला विस्तार</b><span>सूर्योदय/सूर्यास्त और ग्रह उदय-अस्त को उच्च-सटीकता पर्यवेक्षक प्रदाता जोड़ने पर समय-सीमा के साथ दिखाया जाएगा।</span></article></section>}
  {tab==='निरीक्षण'&&<section className="sl-observe"><button onClick={getLocation} className="sl-primary"><Crosshair/> {locating?'स्थान लिया जा रहा है…':'मेरी वर्तमान स्थिति से गणना करें'}</button><div className="sl-observe-card"><Compass/><div><b>पर्यवेक्षक</b><span>{observer.name}</span><small>अक्षांश {observer.lat.toFixed(5)}° · देशांतर {observer.lon.toFixed(5)}°</small></div></div><div className="sl-observe-card"><Globe2/><div><b>समन्वय प्रणाली</b><span>क्रांतिवृत्तीय + स्थानीय क्षितिज</span><small>दीर्घांश, ऊँचाई, अज़ीमुथ और निरयन विभाजन</small></div></div></section>}
 </main><div className="sl-ai"><button onClick={()=>onAsk?.('आकाश प्रयोगशाला में अभी क्या महत्वपूर्ण है?')}><Search/></button><input placeholder="ऐस्ट्रोसुन से आकाश के बारे में पूछें…" onKeyDown={e=>e.key==='Enter'&&onAsk?.(e.currentTarget.value)}/><button><MicIcon/></button></div></div>}
function MicIcon(){return <span className="sl-mic">●</span>}
