import http from'node:http';
import{Pool}from'pg';
import*as store from'../api/db-adapter.mjs';
import{chatWithProviders,providerStatus}from'./provider-runtime.mjs';
const port=Number(process.env.PORT||10000);
const databaseUrl=process.env.DATABASE_URL;
const useDb=Boolean(databaseUrl&&databaseUrl!=='${ASTROSUN_DATABASE_URL}'&&!databaseUrl.includes('base'));
const pool=useDb?new Pool({connectionString:databaseUrl,ssl:{rejectUnauthorized:false},max:5}):null;
const allowedOrigins=new Set(['https://astrosun.onrender.com','https://astrosunn-raghav549s-projects.vercel.app','https://astrosunn-git-main-raghav549s-projects.vercel.app','http://localhost:5173','http://localhost:4173']);
async function migrate(){if(!pool)return;await pool.query(`create table if not exists user_profiles(user_id text primary key,language text not null default 'en',theme text not null default 'system',unit_system text not null default 'metric',location_name text not null default 'Patna',latitude_deg double precision not null default 25.5941,longitude_deg double precision not null default 85.1376,time_zone text not null default 'Asia/Kolkata',rule_set text not null default 'regional:north-india',precision_provider text not null default 'baseline',updated_at timestamptz not null default now());create table if not exists calculation_history(id bigserial primary key,user_id text not null,feature text not null,payload jsonb not null,created_at timestamptz not null default now());create table if not exists research_sources(source_id text primary key,title text not null,url text,provider text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());`)}
function cors(req){const origin=req.headers.origin;const h={'access-control-allow-methods':'GET,POST,PUT,OPTIONS','access-control-allow-headers':'Content-Type, X-AstroSun-User','cache-control':'no-store','content-type':'application/json; charset=utf-8'};if(origin&&allowedOrigins.has(origin))h['access-control-allow-origin']=origin;return h}
function send(req,res,status,body){res.writeHead(status,cors(req));res.end(JSON.stringify(body))}
async function json(req){let s='';for await(const c of req)s+=c;if(s.length>512000)throw Error('Request too large');return s?JSON.parse(s):{}}
async function getProfile(id){if(pool){const r=await pool.query('select * from user_profiles where user_id=$1',[id]);return r.rows[0]||null}return store.getProfile(id)}
async function saveProfile(id,p){if(pool){const r=await pool.query(`insert into user_profiles(user_id,language,theme,unit_system,location_name,latitude_deg,longitude_deg,time_zone,rule_set,precision_provider,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()) on conflict(user_id) do update set language=excluded.language,theme=excluded.theme,unit_system=excluded.unit_system,location_name=excluded.location_name,latitude_deg=excluded.latitude_deg,longitude_deg=excluded.longitude_deg,time_zone=excluded.time_zone,rule_set=excluded.rule_set,precision_provider=excluded.precision_provider,updated_at=now() returning *`,[id,p.language,p.theme,p.unitSystem,p.locationName,p.latitude,p.longitude,p.timeZone,p.ruleSet,p.precisionProvider]);return r.rows[0]}return store.saveProfile(id,p)}
async function addHistory(id,f,payload){if(pool){const r=await pool.query('insert into calculation_history(user_id,feature,payload) values($1,$2,$3) returning id,created_at',[id,f,payload]);return r.rows[0]}return store.addHistory(id,f,payload)}
async function getHistory(id,f){if(pool){const r=f?await pool.query('select id,feature,payload,created_at from calculation_history where user_id=$1 and feature=$2 order by created_at desc limit 100',[id,f]):await pool.query('select id,feature,payload,created_at from calculation_history where user_id=$1 order by created_at desc limit 100',[id]);return r.rows}return store.getHistory(id,f)}
async function handler(req,res){if(req.method==='OPTIONS')return send(req,res,204,{});const u=new URL(req.url,'http://localhost');try{
if(u.pathname==='/api/health'){let db='fallback';if(pool){try{const r=await pool.query('select now()');db=r.rows[0]?'connected':'error'}catch{db='error'}}return send(req,res,200,{ok:true,service:'astrosun-api',database:db,persistence:pool?'postgres':'render-safe-store',providers:providerStatus(process.env).map(p=>({id:p.id,label:p.label,enabled:p.enabled})),serverTime:new Date().toISOString()})}
if(u.pathname==='/api/profile'&&(req.method==='GET'||req.method==='PUT')){const id=req.headers['x-astrosun-user']?.toString()||u.searchParams.get('userId')||'local-user';if(req.method==='GET')return send(req,res,200,{profile:await getProfile(id)});const b=await json(req);const p={language:String(b.language||'en'),theme:['light','dark','system'].includes(b.theme)?b.theme:'system',unitSystem:['metric','imperial'].includes(b.unitSystem)?b.unitSystem:'metric',locationName:String(b.location?.name||'Patna'),latitude:Number(b.location?.latitudeDeg??25.5941),longitude:Number(b.location?.longitudeDeg??85.1376),timeZone:String(b.location?.timeZone||'Asia/Kolkata'),ruleSet:String(b.ruleSet||'regional:north-india'),precisionProvider:String(b.precisionProvider||'baseline')};if(!Number.isFinite(p.latitude)||!Number.isFinite(p.longitude))throw Error('Invalid coordinates');return send(req,res,200,{profile:await saveProfile(id,p)})}
if(u.pathname==='/api/history'&&req.method==='POST'){const b=await json(req);const id=req.headers['x-astrosun-user']?.toString()||'local-user';return send(req,res,201,await addHistory(id,String(b.feature||'unknown'),b.payload??{}))}
if(u.pathname==='/api/history'&&req.method==='GET'){const id=req.headers['x-astrosun-user']?.toString()||u.searchParams.get('userId')||'local-user';return send(req,res,200,{history:await getHistory(id,u.searchParams.get('feature'))})}
if(u.pathname==='/api/research/sources'&&req.method==='GET')return send(req,res,200,{sources:[{source_id:'2606.27055',title:'Solar-system positions and events',url:'https://alphaxiv.org/abs/2606.27055',provider:'alphaXiv'},{source_id:'2609.08979',title:'Relativistic coordinate time scales',url:'https://alphaxiv.org/abs/2609.08979',provider:'alphaXiv'},{source_id:'2601.06452',title:'Modern astrodynamics library',url:'https://alphaxiv.org/abs/2601.06452',provider:'alphaXiv'},{source_id:'2608.19413',title:'Scientific visualization infrastructure',url:'https://alphaxiv.org/abs/2608.19413',provider:'alphaXiv'}]});
if(u.pathname==='/api/ai/chat'&&req.method==='POST'){const b=await json(req);const messages=Array.isArray(b.messages)?b.messages.map((m)=>({role:['system','user','assistant'].includes(m?.role)?m.role:'user',content:String(m?.content||'')})):[];if(!messages.length)throw Error('messages required');const result=await chatWithProviders(messages,process.env,b.context&&typeof b.context==='object'?b.context:{});return send(req,res,200,result)}
if(u.pathname==='/api/providers'&&req.method==='GET')return send(req,res,200,{providers:providerStatus(process.env).map(p=>({id:p.id,label:p.label,baseUrl:p.baseUrl,enabled:p.enabled,model:p.model||'',description:'Configured through Render environment variables'}))});
return send(req,res,404,{ok:false,error:'Not found'})}catch(e){return send(req,res,500,{ok:false,error:e instanceof Error?e.message:String(e)})}}
migrate().then(()=>http.createServer(handler).listen(port,'0.0.0.0',()=>console.log(`AstroSun API listening on ${port}; persistence=${pool?'postgres':'render-safe-store'}`))).catch(e=>{console.error('AstroSun API startup failed',e);process.exit(1)})
