const providerStatus=(env)=>[
{id:'nasa-horizons',label:'NASA/JPL Horizons',baseUrl:'https://ssd-api.jpl.nasa.gov/horizons.api',enabled:true},
{id:'nasa-api',label:'NASA Open APIs',baseUrl:'https://api.nasa.gov',enabled:Boolean(env.NASA_API_KEY)},
{id:'nvidia-nim',label:'NVIDIA NIM',baseUrl:(env.NVIDIA_NIM_BASE_URL||'https://integrate.api.nvidia.com/v1'),enabled:Boolean(env.NVIDIA_NIM_API_KEY),model:env.NVIDIA_NIM_MODEL||''},
{id:'openai-compatible',label:'OpenAI-compatible provider',baseUrl:env.AI_PROVIDER_BASE_URL||'',enabled:Boolean(env.AI_PROVIDER_API_KEY&&env.AI_PROVIDER_BASE_URL),model:env.AI_PROVIDER_MODEL||''},
{id:'aihubmix',label:'AIHubMix',baseUrl:(env.AIHUBMIX_BASE_URL||'https://aihubmix.com/v1'),enabled:Boolean(env.AIHUBMIX_API_KEY),model:env.AIHUBMIX_MODEL||''}
];
const aiConfigs=(env)=>providerStatus(env).filter(p=>['nvidia-nim','openai-compatible','aihubmix'].includes(p.id)&&p.enabled).map(p=>({...p,key:p.id==='nvidia-nim'?env.NVIDIA_NIM_API_KEY:p.id==='openai-compatible'?env.AI_PROVIDER_API_KEY:env.AIHUBMIX_API_KEY}));
export async function chatWithProviders(messages,env,context={}){let lastError=null;for(const p of aiConfigs(env)){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const r=await fetch(`${p.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json',authorization:`Bearer ${p.key}`},body:JSON.stringify({model:p.model||'default',messages,temperature:0.2})});if(!r.ok)throw new Error(`${p.label} HTTP ${r.status}`);const data=await r.json();const text=data?.choices?.[0]?.message?.content;if(typeof text==='string'&&text.trim())return{provider:p.label,model:String(data?.model||p.model||'default'),text,usage:data?.usage,fallback:false}}finally{clearTimeout(timer)}}catch(e){lastError=e}}return{provider:'local-deterministic',model:'astrosun-local',text:`AstroSun local reasoning is active. No configured remote AI provider returned a response.${lastError?` Last provider error: ${lastError instanceof Error?lastError.message:String(lastError)}.`:''}${Object.keys(context).length?` Context keys: ${Object.keys(context).join(', ')}.`:''}`,fallback:true}}
export{providerStatus};
