export const SUPPORTED_LANGUAGES = ['en','hi','bn','mr','ta','te','kn','ml','gu'] as const;
export type LanguageCode = typeof SUPPORTED_LANGUAGES[number];
export type TranslationKey = keyof typeof en;
const en = {
  appName:'ASTROSUN', home:'Home', explore:'Explore', calendar:'Calendar', research:'Research', settings:'Settings', language:'Language', chooseLanguage:'Choose language', continue:'Continue', back:'Back', save:'Save', calculate:'Calculate', reset:'Reset', input:'Input', birthData:'Birth data', birthDate:'Birth date', birthTime:'Birth time', birthPlace:'Birth place', latitude:'Latitude', longitude:'Longitude', timezone:'Time zone', ruleSet:'Rule set', precision:'Precision / provider', today:'Today', panchanga:'Panchanga', kundli:'Kundli', patra:'Patra', graha:'Graha', bhava:'Bhava', nakshatra:'Nakshatra', dasha:'Dasha', transits:'Transits', muhurta:'Muhurta', vivah:'Vivah', rituals:'Sanskara', gemstones:'Gemstones', palm:'Palm analysis', evidence:'Evidence', askAbout:'Ask AstroSun about', noData:'No data', computed:'Computed', traditional:'Traditional', scientificBoundary:'Scientific boundary', approximate:'Approximate', highPrecision:'High precision provider', chart:'Chart', rashi:'Rashi', lagna:'Lagna', moon:'Moon', sun:'Sun', planets:'Planets', houses:'Houses', tithi:'Tithi', yoga:'Yoga', karana:'Karana', pada:'Pada', nakshatraRuler:'Nakshatra ruler', dosha:'Dosha', yogaCombinations:'Yoga / combinations', dashaTimeline:'Dasha timeline', transitMatrix:'Transit matrix', compatibility:'Compatibility', score:'Score', stoneRecommendation:'Stone recommendation', materialScience:'Material science', traditionalJyotisha:'Traditional Jyotisha', methodology:'Methodology', provenance:'Provenance', measurementLayer:'Measurement layer', interpretationLayer:'Interpretation layer', uploadImage:'Upload image', chooseFile:'Choose image', analysis:'Analysis', recommendations:'Recommendations', languageApplied:'Language applied', system:'System', light:'Light', dark:'Dark', metric:'Metric', imperial:'Imperial', connected:'Connected', liveSnapshot:'Live snapshot', opening:'Opening…'
} as const;
const hi = {home:'होम',explore:'एक्सप्लोर',calendar:'कैलेंडर',research:'रिसर्च',settings:'सेटिंग्स',language:'भाषा',chooseLanguage:'भाषा चुनें',continue:'आगे बढ़ें',back:'वापस',save:'सहेजें',calculate:'गणना करें',reset:'रीसेट',input:'इनपुट',birthData:'जन्म डेटा',birthDate:'जन्म तिथि',birthTime:'जन्म समय',birthPlace:'जन्म स्थान',latitude:'अक्षांश',longitude:'देशांतर',timezone:'समय क्षेत्र',ruleSet:'नियम सेट',precision:'प्रिसीजन / प्रोवाइडर',today:'आज',panchanga:'पंचांग',kundli:'कुंडली',patra:'पत्र',graha:'ग्रह',bhava:'भाव',nakshatra:'नक्षत्र',dasha:'दशा',transits:'गोचर',muhurta:'मुहूर्त',vivah:'विवाह',rituals:'संस्कार',gemstones:'रत्न',palm:'हस्त विश्लेषण',evidence:'साक्ष्य',askAbout:'AstroSun से पूछें',noData:'डेटा उपलब्ध नहीं',computed:'गणना किया गया',traditional:'पारंपरिक',scientificBoundary:'वैज्ञानिक सीमा',approximate:'अनुमानित',highPrecision:'हाई-प्रिसीजन प्रोवाइडर',chart:'कुंडली चार्ट',rashi:'राशि',lagna:'लग्न',moon:'चंद्र',sun:'सूर्य',planets:'ग्रह',houses:'भाव',tithi:'तिथि',yoga:'योग',karana:'करण',pada:'पाद',nakshatraRuler:'नक्षत्र स्वामी',dosha:'दोष',yogaCombinations:'योग / संयोजन',dashaTimeline:'दशा समयरेखा',transitMatrix:'गोचर मैट्रिक्स',compatibility:'मिलान',score:'स्कोर',stoneRecommendation:'रत्न सुझाव',materialScience:'सामग्री विज्ञान',traditionalJyotisha:'पारंपरिक ज्योतिष',methodology:'पद्धति',provenance:'स्रोत-प्रमाण',measurementLayer:'मापन परत',interpretationLayer:'व्याख्या परत',uploadImage:'छवि अपलोड करें',chooseFile:'छवि चुनें',analysis:'विश्लेषण',recommendations:'सुझाव',languageApplied:'भाषा लागू',system:'सिस्टम',light:'लाइट',dark:'डार्क',metric:'मीट्रिक',imperial:'इम्पीरियल',connected:'कनेक्टेड',liveSnapshot:'लाइव स्नैपशॉट',opening:'खुल रहा है…'} as Partial<typeof en>;
const bn = {home:'হোম',explore:'এক্সপ্লোর',calendar:'ক্যালেন্ডার',research:'গবেষণা',settings:'সেটিংস',language:'ভাষা',chooseLanguage:'ভাষা নির্বাচন করুন',continue:'চালিয়ে যান',back:'ফিরে যান',save:'সংরক্ষণ',calculate:'গণনা করুন',birthData:'জন্ম তথ্য',birthDate:'জন্ম তারিখ',birthTime:'জন্ম সময়',birthPlace:'জন্মস্থান',panchanga:'পঞ্জিকা',kundli:'কুণ্ডলী',graha:'গ্রহ',bhava:'ভাব',nakshatra:'নক্ষত্র',dasha:'দশা',transits:'গোচর',muhurta:'মুহূর্ত',vivah:'বিবাহ',rituals:'সংস্কার',gemstones:'রত্ন',palm:'হস্ত বিশ্লেষণ',evidence:'প্রমাণ',chart:'জন্মছক',rashi:'রাশি',lagna:'লগ্ন',moon:'চন্দ্র',sun:'সূর্য',planets:'গ্রহগুলি',houses:'ভাবগুলি',tithi:'তিথি',yoga:'যোগ',karana:'করণ',pada:'পদ',compatibility:'সামঞ্জস্য',score:'স্কোর'} as Partial<typeof en>;
const mr = {home:'मुख्यपृष्ठ',explore:'अन्वेषण',calendar:'दिनदर्शिका',research:'संशोधन',settings:'सेटिंग्ज',language:'भाषा',chooseLanguage:'भाषा निवडा',continue:'पुढे चला',back:'मागे',save:'जतन करा',calculate:'गणना करा',panchanga:'पंचांग',kundli:'कुंडली',graha:'ग्रह',bhava:'भाव',nakshatra:'नक्षत्र',dasha:'दशा',transits:'गोचर',muhurta:'मुहूर्त',vivah:'विवाह',rituals:'संस्कार',gemstones:'रत्ने',palm:'हस्त विश्लेषण',evidence:'पुरावा',chart:'कुंडली चार्ट',rashi:'राशी',lagna:'लग्न',moon:'चंद्र',sun:'सूर्य',planets:'ग्रह',houses:'भाव'} as Partial<typeof en>;
const ta = {home:'முகப்பு',explore:'ஆராய்ச்சி',calendar:'நாட்காட்டி',research:'ஆய்வு',settings:'அமைப்புகள்',language:'மொழி',chooseLanguage:'மொழியைத் தேர்ந்தெடுக்கவும்',continue:'தொடரவும்',back:'பின்செல்',save:'சேமி',calculate:'கணக்கிடு',panchanga:'பஞ்சாங்கம்',kundli:'ஜாதகம்',graha:'கிரகம்',bhava:'பாவம்',nakshatra:'நட்சத்திரம்',dasha:'தசா',transits:'கோசாரம்',muhurta:'முஹூர்த்தம்',vivah:'திருமணம்',rituals:'சம்ஸ்காரம்',gemstones:'ரத்தினங்கள்',palm:'கைரேகை பகுப்பாய்வு',evidence:'சான்றுகள்',chart:'ஜாதக அட்டவணை',rashi:'ராசி',lagna:'லக்னம்',moon:'சந்திரன்',sun:'சூரியன்'} as Partial<typeof en>;
const te = {home:'హోమ్',explore:'అన్వేషణ',calendar:'క్యాలెండర్',research:'పరిశోధన',settings:'సెట్టింగ్స్',language:'భాష',chooseLanguage:'భాష ఎంచుకోండి',continue:'కొనసాగించండి',back:'వెనక్కి',save:'సేవ్',calculate:'లెక్కించు',panchanga:'పంచాంగం',kundli:'కుండలి',graha:'గ్రహాలు',bhava:'భావం',nakshatra:'నక్షత్రం',dasha:'దశ',transits:'గోచారం',muhurta:'ముహూర్తం',vivah:'వివాహం',rituals:'సంస్కారాలు',gemstones:'రత్నాలు',palm:'హస్త విశ్లేషణ',evidence:'ఆధారాలు',chart:'జాతక చార్ట్',rashi:'రాశి',lagna:'లగ్నం',moon:'చంద్రుడు',sun:'సూర్యుడు'} as Partial<typeof en>;
const kn = {home:'ಮುಖಪುಟ',explore:'ಅನ್ವೇಷಣೆ',calendar:'ಕ್ಯಾಲೆಂಡರ್',research:'ಸಂಶೋಧನೆ',settings:'ಸೆಟ್ಟಿಂಗ್ಸ್',language:'ಭಾಷೆ',chooseLanguage:'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',continue:'ಮುಂದುವರಿಸಿ',back:'ಹಿಂದೆ',save:'ಉಳಿಸಿ',calculate:'ಲೆಕ್ಕಿಸಿ',panchanga:'ಪಂಚಾಂಗ',kundli:'ಕುಂಡಲಿ',graha:'ಗ್ರಹ',bhava:'ಭಾವ',nakshatra:'ನಕ್ಷತ್ರ',dasha:'ದಶಾ',transits:'ಗೋಚಾರ',muhurta:'ಮುಹೂರ್ತ',vivah:'ವಿವಾಹ',rituals:'ಸಂಸ್ಕಾರ',gemstones:'ರತ್ನಗಳು',palm:'ಹಸ್ತ ವಿಶ್ಲೇಷಣೆ',evidence:'ಸಾಕ್ಷ್ಯ',chart:'ಕುಂಡಲಿ ಚಾರ್ಟ್',rashi:'ರಾಶಿ',lagna:'ಲಗ್ನ',moon:'ಚಂದ್ರ',sun:'ಸೂರ್ಯ'} as Partial<typeof en>;
const ml = {home:'ഹോം',explore:'പര്യവേക്ഷണം',calendar:'കലണ്ടർ',research:'ഗവേഷണം',settings:'ക്രമീകരണങ്ങൾ',language:'ഭാഷ',chooseLanguage:'ഭാഷ തിരഞ്ഞെടുക്കുക',continue:'തുടരുക',back:'മടങ്ങുക',save:'സേവ്',calculate:'കണക്കാക്കുക',panchanga:'പഞ്ചാംഗം',kundli:'ജാതകം',graha:'ഗ്രഹങ്ങൾ',bhava:'ഭാവം',nakshatra:'നക്ഷത്രം',dasha:'ദശ',transits:'ഗോചര',muhurta:'മുഹൂർത്തം',vivah:'വിവാഹം',rituals:'സംസ്കാരം',gemstones:'രത്നങ്ങൾ',palm:'കൈരേഖ വിശകലനം',evidence:'തെളിവുകൾ',chart:'ജാതക ചാർട്ട്',rashi:'രാശി',lagna:'ലഗ്നം',moon:'ചന്ദ്രൻ',sun:'സൂര്യൻ'} as Partial<typeof en>;
const gu = {home:'હોમ',explore:'અન્વેષણ',calendar:'કેલેન્ડર',research:'સંશોધન',settings:'સેટિંગ્સ',language:'ભાષા',chooseLanguage:'ભાષા પસંદ કરો',continue:'ચાલુ રાખો',back:'પાછા',save:'સાચવો',calculate:'ગણતરી કરો',panchanga:'પંચાંગ',kundli:'કુંડળી',graha:'ગ્રહ',bhava:'ભાવ',nakshatra:'નક્ષત્ર',dasha:'દશા',transits:'ગોચર',muhurta:'મુહૂર્ત',vivah:'વિવાહ',rituals:'સંસ્કાર',gemstones:'રત્નો',palm:'હસ્ત વિશ્લેષણ',evidence:'પુરાવા',chart:'કુંડળી ચાર્ટ',rashi:'રાશિ',lagna:'લગ્ન',moon:'ચંદ્ર',sun:'સૂર્ય'} as Partial<typeof en>;
export const DICT:Record<LanguageCode, typeof en> = {en,hi:{...en,...hi},bn:{...en,...bn},mr:{...en,...mr},ta:{...en,...ta},te:{...en,...te},kn:{...en,...kn},ml:{...en,...ml},gu:{...en,...gu}};
export function tr(lang:LanguageCode,key:TranslationKey|string){return DICT[lang]?.[key as TranslationKey] ?? en[key as TranslationKey] ?? key;}
