// AstroSun: compact verified page registry for the mobile 2.5D shell.
export const ASTROSUN_PAGE_CATALOG = [
  {id:'home',group:'core',title:'Home'}, {id:'explore',group:'core',title:'Explore'}, {id:'panchanga',group:'calendar',title:'Panchanga'}, {id:'kundali',group:'jyotisha',title:'Kundali'}, {id:'research',group:'research',title:'Research Vault'}, {id:'settings',group:'system',title:'Settings'},
  {id:'sky',group:'astronomy',title:'Sky Lab'}, {id:'ephemeris',group:'astronomy',title:'Ephemeris'}, {id:'planets',group:'astronomy',title:'Planet Explorer'}, {id:'moon',group:'astronomy',title:'Moon Lab'}, {id:'sun',group:'astronomy',title:'Sun Lab'}, {id:'stars',group:'astronomy',title:'Star Atlas'}, {id:'constellations',group:'astronomy',title:'Constellations'}, {id:'galaxies',group:'astronomy',title:'Galaxy Atlas'}, {id:'nebulae',group:'astronomy',title:'Nebula Explorer'}, {id:'coordinates',group:'astronomy',title:'Coordinate Lab'},
  {id:'observer',group:'observation',title:'Observer Lab'}, {id:'rise-set',group:'observation',title:'Rise / Set'}, {id:'refraction',group:'observation',title:'Refraction'}, {id:'horizon',group:'observation',title:'Horizon'}, {id:'topocentric',group:'observation',title:'Topocentric Geometry'}, {id:'apparent-disk',group:'observation',title:'Apparent Disk'}, {id:'local-sky',group:'observation',title:'Local Sky'}, {id:'visibility',group:'observation',title:'Visibility'},
  {id:'eclipse',group:'events',title:'Eclipse Lab'}, {id:'solar-eclipse',group:'events',title:'Solar Eclipse'}, {id:'lunar-eclipse',group:'events',title:'Lunar Eclipse'}, {id:'conjunctions',group:'events',title:'Conjunctions'}, {id:'oppositions',group:'events',title:'Oppositions'}, {id:'transits',group:'events',title:'Transits'}, {id:'sky-events',group:'events',title:'Sky Events'}, {id:'event-search',group:'events',title:'Event Search'},
  {id:'astrophysics',group:'physics',title:'Astrophysics'}, {id:'relativity',group:'physics',title:'Relativity'}, {id:'compactness',group:'physics',title:'Compact Objects'}, {id:'escape-velocity',group:'physics',title:'Escape Velocity'}, {id:'stellar-physics',group:'physics',title:'Stellar Physics'}, {id:'radiation',group:'physics',title:'Radiation'}, {id:'thermodynamics',group:'physics',title:'Thermal Physics'}, {id:'black-holes',group:'physics',title:'Black Holes'},
  {id:'cosmology',group:'cosmology',title:'Cosmology'}, {id:'lcdm',group:'cosmology',title:'Flat ΛCDM'}, {id:'critical-density',group:'cosmology',title:'Critical Density'}, {id:'cosmic-age',group:'cosmology',title:'Cosmic Age'}, {id:'lookback',group:'cosmology',title:'Lookback Time'}, {id:'hubble',group:'cosmology',title:'Hubble Flow'}, {id:'deceleration',group:'cosmology',title:'Deceleration Parameter'}, {id:'flatness',group:'cosmology',title:'Flatness'},
  {id:'dynamics',group:'dynamics',title:'Dynamics'}, {id:'kepler',group:'dynamics',title:'Kepler Solver'}, {id:'nbody',group:'dynamics',title:'N-Body'}, {id:'integrators',group:'dynamics',title:'Integrators'}, {id:'state-vectors',group:'dynamics',title:'State Vectors'}, {id:'propagation',group:'dynamics',title:'Propagation'}, {id:'covariance',group:'dynamics',title:'Covariance'}, {id:'invariants',group:'dynamics',title:'Dynamics Invariants'},
  {id:'time-scales',group:'time',title:'Time Scales'}, {id:'utc',group:'time',title:'UTC'}, {id:'tai',group:'time',title:'TAI'}, {id:'tt',group:'time',title:'TT'}, {id:'tdb',group:'time',title:'TDB'}, {id:'tcb',group:'time',title:'TCB'}, {id:'earth-orientation',group:'time',title:'Earth Orientation'}, {id:'julian-date',group:'time',title:'Julian Date'},
  {id:'panchanga',group:'calendar',title:'Panchanga'}, {id:'tithi',group:'calendar',title:'Tithi'}, {id:'nakshatra',group:'calendar',title:'Nakshatra'}, {id:'yoga',group:'calendar',title:'Yoga'}, {id:'karana',group:'calendar',title:'Karana'}, {id:'vara',group:'calendar',title:'Vara'}, {id:'ayanamsa',group:'calendar',title:'Ayanamsa'}, {id:'regional-calendar',group:'calendar',title:'Regional Calendar'}, {id:'day-boundary',group:'calendar',title:'Day Boundary'},
  {id:'kundali',group:'jyotisha',title:'Kundali'}, {id:'birth-data',group:'jyotisha',title:'Birth Data'}, {id:'lagna',group:'jyotisha',title:'Lagna'}, {id:'houses',group:'jyotisha',title:'Houses'}, {id:'nakshatra-chart',group:'jyotisha',title:'Nakshatra Chart'}, {id:'dasha',group:'jyotisha',title:'Dasha'}, {id:'muhurta',group:'jyotisha',title:'Muhurta'}, {id:'jyotisha-evidence',group:'jyotisha',title:'Jyotisha Evidence'},
  {id:'research',group:'research',title:'Research Vault'}, {id:'literature',group:'research',title:'Literature Map'}, {id:'evidence-graph',group:'research',title:'Evidence Graph'}, {id:'provenance',group:'research',title:'Provenance'}, {id:'citations',group:'research',title:'Citations'}, {id:'paper-reader',group:'research',title:'Paper Reader'}, {id:'research-notes',group:'research',title:'Research Notes'}, {id:'open-science',group:'research',title:'Open Science'},
  {id:'benchmarks',group:'validation',title:'Benchmarks'}, {id:'validation-matrix',group:'validation',title:'Validation Matrix'}, {id:'uncertainty',group:'validation',title:'Uncertainty'}, {id:'error-ellipse',group:'validation',title:'Error Ellipse'}, {id:'accuracy-policy',group:'validation',title:'Accuracy Policy'}, {id:'kernel-manifest',group:'validation',title:'Kernel Manifest'}, {id:'provider-registry',group:'validation',title:'Provider Registry'}, {id:'quality',group:'validation',title:'Quality & Provenance'},
  {id:'profile',group:'system',title:'Profile'}, {id:'preferences',group:'system',title:'Preferences'}, {id:'language',group:'system',title:'Language'}, {id:'appearance',group:'system',title:'Appearance'}, {id:'data',group:'system',title:'Data'}, {id:'about',group:'system',title:'About'}, {id:'diagnostics',group:'system',title:'Diagnostics'}, {id:'offline',group:'system',title:'Offline Center'},
  {id:'ai-council',group:'ai',title:'AI Council'}, {id:'evidence-ai',group:'ai',title:'Evidence AI'}, {id:'explain',group:'ai',title:'Explain a Result'}, {id:'compare',group:'ai',title:'Compare Results'}, {id:'assistant',group:'ai',title:'Research Assistant'}, {id:'prompt-lab',group:'ai',title:'Prompt Lab'}, {id:'source-check',group:'ai',title:'Source Check'}, {id:'claim-check',group:'ai',title:'Claim Check'},
  {id:'library',group:'resources',title:'Science Library'}, {id:'datasets',group:'resources',title:'Datasets'}, {id:'kernels',group:'resources',title:'Ephemeris Kernels'}, {id:'formulas',group:'resources',title:'Formula Library'}, {id:'constants',group:'resources',title:'Physical Constants'}, {id:'glossary',group:'resources',title:'Astronomy Glossary'}, {id:'tutorials',group:'resources',title:'Tutorials'}, {id:'learn',group:'resources',title:'Learning Paths'}
];

export const ASTROSUN_PAGE_COUNT=new Set(ASTROSUN_PAGE_CATALOG.map(x=>x.group+':'+x.id)).size;
