import type { JyotishaChart, GrahaPoint } from '../panchanga/jyotisha';
import { nakshatraAt, signAt, wholeSignHouses } from './workspace-engine';
const mod=(x:number)=>((x%360)+360)%360;
const GRAHAS=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'] as const;
const own:Record<string,string[]>={Sun:['Leo'],Moon:['Cancer'],Mars:['Aries','Scorpio'],Mercury:['Gemini','Virgo'],Jupiter:['Sagittarius','Pisces'],Venus:['Taurus','Libra'],Saturn:['Capricorn','Aquarius'],Rahu:[],Ketu:[]};
const exalt:Record<string,string>={Sun:'Aries',Moon:'Taurus',Mars:'Capricorn',Mercury:'Virgo',Jupiter:'Cancer',Venus:'Pisces',Saturn:'Libra'};
const debilitated:Record<string,string>={Sun:'Libra',Moon:'Scorpio',Mars:'Cancer',Mercury:'Pisces',Jupiter:'Capricorn',Venus:'Virgo',Saturn:'Aries'};
const signs=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const lords:Record<string,string>={Aries:'Mars',Taurus:'Venus',Gemini:'Mercury',Cancer:'Moon',Leo:'Sun',Virgo:'Mercury',Libra:'Venus',Scorpio:'Mars',Sagittarius:'Jupiter',Capricorn:'Saturn',Aquarius:'Saturn',Pisces:'Jupiter'};
export function houseOf(point:number,asc:number){return((Math.floor(mod(point)/30)-Math.floor(mod(asc)/30)+12)%12)+1;}
export function grahaDignity(p:GrahaPoint){const s=signAt(p.longitudeDeg);return exalt[p.name]===s?'Exalted':debilitated[p.name]===s?'Debilitated':own[p.name]?.includes(s)?'Own sign':'Neutral baseline';}
export function traditionalAspects(chart:JyotishaChart){const asc=chart.ascendant.longitudeDeg;return chart.planets.flatMap(p=>{const sourceHouse=houseOf(p.longitudeDeg,asc);const offsets=p.name==='Mars'?[4,7,8]:p.name==='Jupiter'?[5,7,9]:p.name==='Saturn'?[3,7,10]:[7];return offsets.map(offset=>({planet:p.name,fromHouse:sourceHouse,toHouse:((sourceHouse-1+offset)%12)+1,traditional:true}));});}
export function yogaCandidates(chart:JyotishaChart){const points=chart.planets;const bySign=new Map<string,string[]>();for(const p of points){const s=signAt(p.longitudeDeg);if(!bySign.has(s))bySign.set(s,[]);bySign.get(s)!.push(p.name);}const out:{name:string;rule:string;confidence:'rule-match'}[]=[];for(const [s,arr] of bySign){if(arr.includes('Sun')&&arr.includes('Mercury'))out.push({name:'Budha-Aditya Yoga',rule:`Sun + Mercury in ${s}`,confidence:'rule-match'});if(arr.includes('Moon')&&arr.includes('Jupiter'))out.push({name:'Gaja-Kesari candidate',rule:`Moon + Jupiter in ${s}`,confidence:'rule-match'});if(arr.includes('Moon')&&arr.includes('Mars'))out.push({name:'Chandra-Mangala candidate',rule:`Moon + Mars in ${s}`,confidence:'rule-match'});}const houses=wholeSignHouses(chart.ascendant.longitudeDeg);for(const h of houses){const lord=lords[h.sign];if(points.some(p=>p.name===lord&&[1,4,7,10].includes(h.house)))out.push({name:'Kendra lord candidate',rule:`${lord} connected to ${h.house}th house`,confidence:'rule-match'});}return out;}
export function doshaCandidates(chart:JyotishaChart){const asc=chart.ascendant.longitudeDeg;const moon=chart.moon.longitudeDeg;const mars=chart.planets.find(p=>p.name==='Mars');const marsH=mars?houseOf(mars.longitudeDeg,asc):0;const marsMoonH=mars?houseOf(mars.longitudeDeg,moon):0;const mangal=[1,2,4,7,8,12].includes(marsH)||[1,2,4,7,8,12].includes(marsMoonH);const nodes=chart.planets.filter(p=>p.name==='Rahu'||p.name==='Ketu');const kaalSarpaCandidate=nodes.length===2;return{mangalDosha:mangal,kaalSarpaCandidate,notes:['Traditional rule candidates; schools differ and these are not scientific diagnoses.']};}
export function vargaSign(longitudeDeg:number,division:number){const sign=Math.floor(mod(longitudeDeg)/30),within=(mod(longitudeDeg)%30)/30;let v=sign;if(division===2)v=sign*2+(within<.5?0:1);else if(division>2)v=Math.floor(mod(sign+within*division*12)/12);return signs[v%12];}
export function advancedGrahaRows(chart:JyotishaChart){return chart.planets.map(p=>{const sep=mod(p.longitudeDeg-chart.sun.longitudeDeg);return{name:p.name,longitudeDeg:p.longitudeDeg,sign:signAt(p.longitudeDeg),house:houseOf(p.longitudeDeg,chart.ascendant.longitudeDeg),nakshatra:nakshatraAt(p.longitudeDeg),dignity:grahaDignity(p),retrograde:Boolean(p.retrograde),combustionDistanceDeg:Math.min(sep,360-sep),varga:{D1:vargaSign(p.longitudeDeg,1),D2:vargaSign(p.longitudeDeg,2),D9:vargaSign(p.longitudeDeg,9),D10:vargaSign(p.longitudeDeg,10),D12:vargaSign(p.longitudeDeg,12),D24:vargaSign(p.longitudeDeg,24),D60:vargaSign(p.longitudeDeg,60)}};});}
export function classicalGrahas(chart:JyotishaChart){return GRAHAS.map(name=>chart.planets.find(p=>p.name===name)|| (name==='Sun'?chart.sun:name==='Moon'?chart.moon:undefined)).filter(Boolean) as GrahaPoint[];}
