import { computePanchanga } from '../panchanga/engine';
import { buildJyotishaChart } from '../panchanga/jyotisha';
export const VIMSHOTTARI=[['Ketu',7],['Venus',20],['Sun',6],['Moon',10],['Mars',7],['Rahu',18],['Jupiter',16],['Saturn',19],['Mercury',17]] as const;
export const NAKSHATRA_RULERS=VIMSHOTTARI.map(([x])=>x);
const ZODIAC=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishtha','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
const mod360=(x:number)=>((x%360)+360)%360;
export const signAt=(deg:number)=>ZODIAC[Math.floor(mod360(deg)/30)];
export const nakshatraAt=(deg:number)=>{const index=Math.min(26,Math.floor(mod360(deg)/(360/27)));const seg=360/27;return{name:NAKSHATRAS[index],index,pada:Math.min(4,Math.floor((mod360(deg)%seg)/(seg/4))+1),ruler:VIMSHOTTARI[index%9][0]}};
export function wholeSignHouses(ascendantDeg:number){const ascSign=Math.floor(mod360(ascendantDeg)/30);return Array.from({length:12},(_,i)=>({house:i+1,sign:ZODIAC[(ascSign+i)%12],startDeg:((ascSign+i)*30)%360}));}
export function chartSummary(date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string}){computePanchanga(date,{sidereal:true,location,ruleSet:'traditional:jyotisha'});return buildJyotishaChart(date,{...location,longitudeDeg:location.longitudeDeg});}
export function dashaTimeline(birthDate:Date,moonLongitudeDeg:number,yearsForward=24){const n=nakshatraAt(moonLongitudeDeg);const rulerIndex=Math.max(0,VIMSHOTTARI.findIndex(x=>x[0]===n.ruler));const span=360/27;const into=mod360(moonLongitudeDeg)%span;const fractionRemaining=1-into/span;let cursor=new Date(birthDate);const result:Array<{lord:string;start:Date;end:Date;durationYears:number;sequence:number}>=[];let index=rulerIndex;let elapsed=0;let first=true;while(elapsed<yearsForward){const [lord,years]=VIMSHOTTARI[index];const durationYears=first?Number(years)*fractionRemaining:Number(years);const start=new Date(cursor);const end=new Date(cursor.getTime()+durationYears*365.2425*86400000);result.push({lord,start,end,durationYears,sequence:result.length+1});cursor=end;elapsed+=durationYears;index=(index+1)%9;first=false;}return result;}
export function transitTable(natal:ReturnType<typeof buildJyotishaChart>,date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string}){const current=buildJyotishaChart(date,{...location,longitudeDeg:location.longitudeDeg});const transitPoints=[current.sun,current.moon,...current.planets.filter(x=>!['Sun','Moon'].includes(x.name))];return transitPoints.map(t=>{const n=[natal.sun,natal.moon,...natal.planets.filter(x=>!['Sun','Moon'].includes(x.name))].find(x=>x.name===t.name);const separation=mod360(t.longitudeDeg-(n?.longitudeDeg??0));return{planet:t.name,transitDeg:t.longitudeDeg,natalDeg:n?.longitudeDeg??null,separationDeg:Math.min(separation,360-separation),sign:signAt(t.longitudeDeg),nakshatra:nakshatraAt(t.longitudeDeg)}});}
const TITHI_RULES=[1,2,3,5,6,7,10,11,13];
const NAK_RULES=['Ashwini','Rohini','Mrigashira','Punarvasu','Pushya','Hasta','Chitra','Swati','Anuradha','Shravana','Dhanishtha','Revati'];
function timeToMinutes(h:number,m:number){return h*60+m}
function riseSetMinutes(p:{sunrise?:string;sunset?:string}){const parse=(v?:string)=>v?{h:Number(v.slice(0,2)),m:Number(v.slice(3,5))}:null;const a=parse(p.sunrise),b=parse(p.sunset);return a&&b?{sunrise:timeToMinutes(a.h,a.m),sunset:timeToMinutes(b.h,b.m)}:null;}
function localDateKey(d:Date,zone:string){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function daySegmentWindows(rise:number,set:number){const dayLength=set-rise;const eighth=dayLength/8;return{rahukaal:[rise+eighth*7,rise+eighth*8],abhijit:[rise+dayLength*0.45,rise+dayLength*0.55]}}
export function muhurtaCandidates(date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string},hours=24){const out:Array<{time:Date;score:number;tithi:number;tithiName:string;nakshatra:string;nakshatraPada:number;reason:string;tags:string[];solarBoundary:'daylight'|'night'}>=[];const step=30*60000;const start=new Date(date);start.setHours(0,0,0,0);const end=start.getTime()+hours*3600000;for(let ms=start.getTime();ms<end;ms+=step){const at=new Date(ms);const p=computePanchanga(at,{sidereal:true,location,ruleSet:'traditional:muhurta'});const goodTithi=TITHI_RULES.includes(p.tithi.number);const goodNak=NAK_RULES.includes(p.nakshatra.name);const rs=riseSetMinutes(p);const minutes=Number(new Intl.DateTimeFormat('en-GB',{timeZone:location.timeZone,hour:'2-digit',minute:'2-digit',hour12:false}).format(at).replace(':','.'));const hm=Math.floor(minutes)*60+Math.round((minutes-Math.floor(minutes))*100);const daytime=rs?hm>=rs.sunrise&&hm<=rs.sunset:true;const tags:string[]=[];let score=(goodTithi?45:0)+(goodNak?35:0)+(daytime?20:0);if(rs&&daytime){const special=daySegmentWindows(rs.sunrise,rs.sunset);const inRahu=hm>=special.rahukaal[0]&&hm<special.rahukaal[1];const inAbhijit=hm>=special.abhijit[0]&&hm<special.abhijit[1];if(inRahu){score-=40;tags.push('Rahu Kalam')}if(inAbhijit){score=Math.min(100,score+10);tags.push('Abhijit window')}}if(score>=55)out.push({time:at,score:Math.max(0,Math.min(100,score)),tithi:p.tithi.number,tithiName:p.tithi.name,nakshatra:p.nakshatra.name,nakshatraPada:p.nakshatra.pada,reason:`Tithi ${goodTithi?'favorable':'not preferred'}; Nakshatra ${goodNak?'favorable':'not preferred'}${tags.length?`; ${tags.join(', ')}`:''}`,tags,solarBoundary:daytime?'daylight':'night'});void localDateKey;}return out.sort((a,b)=>b.score-a.score||a.time.getTime()-b.time.getTime());}
export function compatibilityScore(a:ReturnType<typeof buildJyotishaChart>,b:ReturnType<typeof buildJyotishaChart>){const amoon=a.moon.longitudeDeg,bmoon=b.moon.longitudeDeg;const an=nakshatraAt(amoon),bn=nakshatraAt(bmoon);const tara=((bn.index-an.index+27)%27)+1;const nadiA=an.index%3,nadiB=bn.index%3;const nadi=nadiA===nadiB?0:8;const bhakoot=Math.abs(Math.floor(amoon/30)-Math.floor(bmoon/30))%12;const bhakootPoints=[0,7,7,7,0,5,7,0,5,7,7,0][bhakoot];const taraPoints=tara%3===0?0:tara%2===0?2:3;const yoni=an.index%14===bn.index%14?4:2;const grahaMaitri=signAt(amoon)===signAt(bmoon)?5:3;const gana=an.index%3===bn.index%3?6:1;const varna=(Math.floor(amoon/90)%4)>=(Math.floor(bmoon/90)%4)?1:0;const total=varna+2+taraPoints+yoni+grahaMaitri+gana+bhakootPoints+nadi;return{total,max:36,components:{varna,vashya:2,tara:taraPoints,yoni,grahaMaitri,gana,bhakoot:bhakootPoints,nadi},note:'Traditional Ashtakoota-style baseline; cultural interpretation, not a scientific predictor.'}}
export const workspaceAccuracy={astronomy:'analytical baseline unless a validated high-precision provider is injected',jyotisha:'traditional rule engine built on calculated astronomical positions',muhurta:'explicit configurable baseline rules including solar day boundaries',compatibility:'traditional scoring model; not scientific evidence'};
