import { computePanchanga } from '../panchanga/engine';
import { buildJyotishaChart } from '../panchanga/jyotisha';

export const VIMSHOTTARI = [['Ketu',7],['Venus',20],['Sun',6],['Moon',10],['Mars',7],['Rahu',18],['Jupiter',16],['Saturn',19],['Mercury',17]] as const;
export const NAKSHATRA_RULERS = VIMSHOTTARI.map(([x]) => x);
const ZODIAC=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishtha','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
const mod360=(x:number)=>((x%360)+360)%360;
export const signAt=(deg:number)=>ZODIAC[Math.floor(mod360(deg)/30)];
export const nakshatraAt=(deg:number)=>{const index=Math.min(26,Math.floor(mod360(deg)/(360/27)));return{name:NAKSHATRAS[index],index,pada:Math.floor((mod360(deg)%(360/27))/(360/108))+1,ruler:VIMSHOTTARI[index%9][0]}};
export function wholeSignHouses(ascendantDeg:number){const ascSign=Math.floor(mod360(ascendantDeg)/30);return Array.from({length:12},(_,i)=>({house:i+1,sign:ZODIAC[(ascSign+i)%12],startDeg:((ascSign+i)*30)%360}));}
export function chartSummary(date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string}){computePanchanga(date,{sidereal:true,location,ruleSet:'traditional:jyotisha'});return buildJyotishaChart(date,{...location,longitudeDeg:location.longitudeDeg});}
export function dashaTimeline(birthDate:Date,moonLongitudeDeg:number,yearsForward=24){const n=nakshatraAt(moonLongitudeDeg);const rulerIndex=Math.max(0,VIMSHOTTARI.findIndex(x=>x[0]===n.ruler));const span=360/27;const into=mod360(moonLongitudeDeg)%span;const fractionRemaining=1-into/span;let cursor=new Date(birthDate);const result:Array<{lord:string;start:Date;end:Date;durationYears:number;sequence:number}>=[];let index=rulerIndex;let elapsed=0;let first=true;while(elapsed<yearsForward){const [lord,years]=VIMSHOTTARI[index];const durationYears=first?years*fractionRemaining:years;const start=new Date(cursor);const end=new Date(cursor.getTime()+durationYears*365.2425*86400000);result.push({lord,start,end,durationYears,sequence:result.length+1});cursor=end;elapsed+=durationYears;index=(index+1)%9;first=false;}return result;}
export function transitTable(natal:ReturnType<typeof buildJyotishaChart>,date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string}){const current=buildJyotishaChart(date,{...location,longitudeDeg:location.longitudeDeg});const points=[current.sun,current.moon];return points.map((t)=>{const n=[natal.sun,natal.moon].find((x)=>x.name===t.name);const separation=mod360(t.longitudeDeg-(n?.longitudeDeg??0));return{planet:t.name,transitDeg:t.longitudeDeg,natalDeg:n?.longitudeDeg??null,separationDeg:Math.min(separation,360-separation),sign:signAt(t.longitudeDeg),nakshatra:nakshatraAt(t.longitudeDeg)}});}
const TITHI_RULES=[1,2,3,5,6,7,10,11,13];
const NAK_RULES=['Ashwini','Rohini','Mrigashira','Punarvasu','Pushya','Hasta','Chitra','Swati','Anuradha','Shravana','Dhanishtha','Revati'];
export function muhurtaCandidates(date:Date,location:{latitudeDeg:number;longitudeDeg:number;timeZone:string},hours=24){const out:Array<{time:Date;score:number;tithi:number;tithiName:string;nakshatra:string;nakshatraPada:number;reason:string}>=[];const step=30*60000;const start=new Date(date);start.setHours(0,0,0,0);for(let t=0;t<hours*2;t++){const at=new Date(start.getTime()+t*step);const p=computePanchanga(at,{sidereal:true,location,ruleSet:'traditional:muhurta'});const goodTithi=TITHI_RULES.includes(p.tithi.number);const goodNak=NAK_RULES.includes(p.nakshatra.name);const score=(goodTithi?60:0)+(goodNak?40:0);if(score>=60)out.push({time:at,score,tithi:p.tithi.number,tithiName:String(p.tithi.number),nakshatra:p.nakshatra.name,nakshatraPada:p.nakshatra.pada,reason:`Tithi ${goodTithi?'favorable':'not preferred'}; Nakshatra ${goodNak?'favorable':'not preferred'}`});}return out;}
export function compatibilityScore(a:ReturnType<typeof buildJyotishaChart>,b:ReturnType<typeof buildJyotishaChart>){const amoon=a.moon.longitudeDeg;const bmoon=b.moon.longitudeDeg;const an=nakshatraAt(amoon),bn=nakshatraAt(bmoon);const tara=((bn.index-an.index+27)%27)+1;const nadiA=an.index%3,nadiB=bn.index%3;const nadi=nadiA===nadiB?0:8;const bhakoot=(Math.abs(Math.floor(amoon/30)-Math.floor(bmoon/30))%12);const bhakootPoints=[0,7,7,7,0,5,7,0,5,7,7,0][bhakoot];const taraPoints=tara%3===0?0:tara%2===0?2:3;const yoni=an.index%14===bn.index%14?4:2;const grahaMaitri=signAt(amoon)===signAt(bmoon)?5:3;const gana=an.index%3===bn.index%3?6:1;const varna=(Math.floor(amoon/90)%4)>=(Math.floor(bmoon/90)%4)?1:0;const total=varna+2+taraPoints+yoni+grahaMaitri+gana+bhakootPoints+nadi;return{total,max:36,components:{varna,vashya:2,tara:taraPoints,yoni,grahaMaitri,gana,bhakoot:bhakootPoints,nadi},note:'Traditional Ashtakoota-style baseline; cultural interpretation, not a scientific predictor.'}}
export const workspaceAccuracy={astronomy:'analytical baseline unless a validated high-precision provider is injected',jyotisha:'traditional rule engine built on calculated astronomical positions',muhurta:'explicit configurable baseline rules',compatibility:'traditional scoring model; not scientific evidence'};