import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Orbit, Telescope, CalendarDays, BookOpen, Settings2, Sparkles, ChevronRight, ShieldCheck, Activity, Atom, Sun, Moon, Globe2, ArrowLeft, Rocket, Search, Zap, CircleDot, Clock3} from 'lucide-react';
import {buildRuntimeSnapshot} from './core';
import {getRegionalPolicy,REGIONAL_PANCHANGA_POLICIES} from './core/panchanga/regional';
import './styles.css';

const toolCards=[
 {id:'sky',title:'Sky Lab',eyebrow:'LIVE SKY',text:'Sun, Moon, planetary positions and observer geometry.',icon:Telescope,accent:'cyan'},
 {id:'panchanga',title:'Panchanga',eyebrow:'CALENDAR',text:'Tithi, Nakshatra, Yoga and Karana with explicit accuracy labels.',icon:CalendarDays,accent:'gold'},
 {id:'astrophysics',title:'Astrophysics',eyebrow:'PHYSICS',text:'Relativity, cosmology, stellar and planetary physics modules.',icon:Atom,accent:'violet'},
 {id:'research',title:'Research Vault',eyebrow:'EVIDENCE',text:'Evidence-aware literature and provenance-oriented research surface.',icon:BookOpen,accent:'pink'},
];

function App(){
 const [intro,setIntro]=useState(true);
 const [page,setPage]=useState('home');
 const [runtime,setRuntime]=useState(()=>buildRuntimeSnapshot());
 useEffect(()=>{const t=setTimeout(()=>setIntro(false),950); return()=>clearTimeout(t)},[]);
 useEffect(()=>{const id=setInterval(()=>setRuntime(buildRuntimeSnapshot()),60000); return()=>clearInterval(id)},[]);
 if(intro) return <div className="splash"><div className="splashOrb"><Orbit/></div><div className="splashTitle">ASTROSUN</div><div className="splashSub">COSMIC INTELLIGENCE PLATFORM</div><div className="splashBar"><span/></div></div>;
 const passed=runtime.invariants.filter(x=>x.passed).length;
 if(page==='panchanga') return <PanchangaPage runtime={runtime} onBack={()=>setPage('home')}/>;
 if(page==='research') return <ResearchPage runtime={runtime} onBack={()=>setPage('home')}/>;
 if(page==='settings') return <SettingsPage onBack={()=>setPage('home')}/>;
 if(page==='sky') return <SkyPage runtime={runtime} onBack={()=>setPage('home')}/>;
 if(page==='astrophysics') return <AstrophysicsPage runtime={runtime} onBack={()=>setPage('home')}/>;
 return <div className="app"><header className="topbar"><div className="brand"><div className="brandIcon"><Orbit/></div><div><b>ASTROSUN</b><span>COSMIC INTELLIGENCE</span></div></div><button className="iconBtn" onClick={()=>setPage('settings')} aria-label="Settings"><Settings2 size={20}/></button></header>
 <main className="homeMain">
   <section className="hero3d"><div className="heroGlow glowOne"/><div className="heroGlow glowTwo"/><div className="orbitRing ringOne"/><div className="orbitRing ringTwo"/><div className="miniSun"><Sun/></div><div className="heroCopy"><div className="eyebrow">SCIENCE × JYOTISHA × EVIDENCE</div><h1>Explore the universe<br/><em>as a system.</em></h1><p>Real computational layers for sky motion, astronomy, astrophysics and Panchanga—kept explicit about what is approximate and what needs high-precision providers.</p><button className="primary3d" onClick={()=>setPage('sky')}>Open Sky Lab <ChevronRight size={18}/></button></div><div className="snapshot3d"><div className="snapshotTop"><span>LIVE SNAPSHOT</span><span className="liveDot">●</span></div><div className="snapshotPlanet"><div className="planetMoon"><Moon/></div><div><b>Moon</b><strong>{runtime.positions.find(x=>x.body==='Moon')?.longitudeDeg.toFixed(2)}°</strong></div></div><div className="snapshotGrid"><div><small>TITHI</small><b>{runtime.panchanga.tithi.number}</b></div><div><small>NAKSHATRA</small><b>{runtime.panchanga.nakshatra.name}</b></div></div></div></section>
   <section className="statusRow"><div className="statusPill"><ShieldCheck size={15}/><span>Invariants <b>{passed}/{runtime.invariants.length}</b></span></div><div className="statusPill"><Activity size={15}/><span>Ephemeris <b>Analytical</b></span></div><div className="statusPill"><Zap size={15}/><span>High precision <b>Provider-ready</b></span></div></section>
   <section className="sectionHead"><div><span className="eyebrow dark">TOOLS</span><h2>Cosmic workbench</h2></div><span className="sectionHint">2.5D workspace</span></section>
   <section className="toolGrid">{toolCards.map((c,i)=>{const I=c.icon;return <button className={`toolCard card-${c.accent}`} key={c.id} onClick={()=>setPage(c.id)}><div className="cardDepth"/><div className="toolIcon"><I size={25}/></div><div className="toolNum">0{i+1}</div><div className="toolBody"><span>{c.eyebrow}</span><h3>{c.title}</h3><p>{c.text}</p></div><div className="cardArrow"><ChevronRight size={18}/></div></button>})}</section>
   <section className="wideCard2d"><div className="wideOrb"><Globe2/></div><div><span className="eyebrow dark">RESEARCH FOUNDATION</span><h2>Modern astronomy, rigorous boundaries.</h2><p>Architecture follows provider contracts, uncertainty layers, benchmarks and explicit provenance so an approximate answer never masquerades as a high-precision result.</p></div><button className="secondary3d" onClick={()=>setPage('research')}>Research Vault <ArrowLeft className="flipArrow" size={16}/></button></section>
   <section className="quickGrid"><button onClick={()=>setPage('panchanga')} className="quickCard"><CalendarDays/><div><b>Today’s Panchanga</b><span>{runtime.panchanga.tithi.paksha} • {runtime.panchanga.nakshatra.name}</span></div><ChevronRight/></button><button onClick={()=>setPage('research')} className="quickCard"><BookOpen/><div><b>Evidence surface</b><span>Provenance & research contracts</span></div><ChevronRight/></button></section>
 </main><nav className="bottomNav"><button className={page==='home'?'active':''} onClick={()=>setPage('home')}><Sparkles/><span>Home</span></button><button className={['sky','astrophysics'].includes(page)?'active':''} onClick={()=>setPage('sky')}><Telescope/><span>Explore</span></button><button className={page==='panchanga'?'active':''} onClick={()=>setPage('panchanga')}><CalendarDays/><span>Calendar</span></button><button className={page==='research'?'active':''} onClick={()=>setPage('research')}><BookOpen/><span>Research</span></button><button className={page==='settings'?'active':''} onClick={()=>setPage('settings')}><Settings2/><span>Settings</span></button></nav>
 </div>
}

function PageShell({title,kicker,onBack,children}){return <div className="app pageShell"><header className="topbar"><button className="iconBtn" onClick={onBack}><ArrowLeft size={20}/></button><div className="pageTitle"><span>{kicker}</span><b>{title}</b></div><div className="brandMini"><Orbit size={18}/></div></header>{children}</div>}
function PanchangaPage({runtime,onBack}){const [rule,setRule]=useState('generic-lunisolar-v1');const regional=useMemo(()=>getRegionalPolicy('north-india'),[]);return <PageShell title="Panchanga" kicker="CALENDAR ENGINE" onBack={onBack}><main className="innerMain"><section className="pageHero panchHero"><div><span className="eyebrow">TODAY</span><h1>{runtime.panchanga.tithi.paksha} Paksha · Tithi {runtime.panchanga.tithi.number}</h1><p>{runtime.panchanga.nakshatra.name} · Yoga {runtime.panchanga.yogaName} · Karana {runtime.panchanga.karanaName}</p></div><div className="calendarDisc"><CalendarDays/></div></section><section className="metricGrid"><Metric icon={CircleDot} label="Moon longitude" value={`${runtime.panchanga.moonLongitudeDeg.toFixed(3)}°`}/><Metric icon={Sun} label="Sun longitude" value={`${runtime.panchanga.sunLongitudeDeg.toFixed(3)}°`}/><Metric icon={Clock3} label="Accuracy" value="Approximate"/></section><section className="formCard2d"><label>Regional policy</label><select value="north-india" disabled><option>North India</option></select><label>Rule set</label><select value={rule} onChange={e=>setRule(e.target.value)}>{['generic-lunisolar-v1'].map(x=><option key={x}>{x}</option>)}</select><div className="policyNote"><b>{regional.name}</b><span>{regional.notes.join(' ')}</span></div></section></main></PageShell>}
function SkyPage({runtime,onBack}){const moon=runtime.positions.find(x=>x.body==='Moon');const sun=runtime.positions.find(x=>x.body==='Sun');return <PageShell title="Sky Lab" kicker="OBSERVATION ENGINE" onBack={onBack}><main className="innerMain"><section className="skyStage"><div className="skyStars">✦ · · ✧ · ✦ · · ✧</div><div className="skySun"><Sun/></div><div className="skyMoon"><Moon/></div><div className="skyOrbitPath"/><div className="skyCenter"><Orbit size={46}/><span>EARTH FRAME</span></div></section><section className="metricGrid"><Metric icon={Sun} label="Sun" value={`${sun?.longitudeDeg.toFixed(2)}°`}/><Metric icon={Moon} label="Moon" value={`${moon?.longitudeDeg.toFixed(2)}°`}/><Metric icon={MapPinFallback} label="Observer" value="Geometry ready"/></section></main></PageShell>}
function AstrophysicsPage({runtime,onBack}){return <PageShell title="Astrophysics" kicker="PHYSICS WORKBENCH" onBack={onBack}><main className="innerMain"><section className="physicsGrid"><PhysicsCard title="Relativity" text="Time dilation, escape velocity and compactness modules." value="Ready"/><PhysicsCard title="Cosmology" text="Flat ΛCDM, critical density, age and lookback integrals." value="Ready"/><PhysicsCard title="Dynamics" text="Kepler, N-body, integrators and covariance substrate." value="Ready"/></section><div className="noticeCard"><ShieldCheck/><div><b>Accuracy boundary active</b><span>Physics formulas are deterministic; observational ephemerides remain provider-labelled.</span></div></div></main></PageShell>}
function ResearchPage({runtime,onBack}){return <PageShell title="Research Vault" kicker="EVIDENCE GRAPH" onBack={onBack}><main className="innerMain"><section className="researchHero"><BookOpen/><div><span className="eyebrow">CURRENT ARCHITECTURE</span><h1>Evidence-aware by design.</h1><p>Provider contracts, provenance and uncertainty remain separate from presentation.</p></div></section><div className="researchList"><ResearchRow title="High-precision ephemeris" state="External DE/SPICE/CALCEPH provider required"/><ResearchRow title="Uncertainty layer" state="Available"/><ResearchRow title="Benchmark gates" state="Available"/><ResearchRow title="Regional Panchanga policies" state={`${Object.keys(REGIONAL_PANCHANGA_POLICIES).length} policy definitions`}/></div></main></PageShell>}
function SettingsPage({onBack}){return <PageShell title="Settings" kicker="APP CONFIG" onBack={onBack}><main className="innerMain"><section className="formCard2d"><label>Interface</label><select defaultValue="2.5d"><option value="2.5d">2.5D Colour Depth</option></select><label>Theme</label><select defaultValue="aurora"><option value="aurora">Aurora light</option></select><div className="policyNote"><b>AstroSun visual system</b><span>Layered cards, colourful gradients, strong depth shadows and responsive mobile-first surfaces.</span></div></section></main></PageShell>}
function Metric({icon:Icon,label,value}){return <div className="metricCard"><div><Icon size={18}/><span>{label}</span></div><b>{value}</b></div>}
function PhysicsCard({title,text,value}){return <div className="physicsCard"><div className="physicsOrb"><Atom/></div><span>MODULE</span><h3>{title}</h3><p>{text}</p><strong>{value}</strong></div>}
function ResearchRow({title,state}){return <div className="researchRow"><div><b>{title}</b><span>{state}</span></div><ShieldCheck size={18}/></div>}
function MapPinFallback(){return <MapPinIcon/>}
function MapPinIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>}

createRoot(document.getElementById('root')).render(<App/>);
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}